### ISSUE TITLE
No public API to customize report method name

### ISSUE THREAD

**Issue by htzhang2** [testng-team/testng#1046]
If test is derived from dataProvider, the test method name is always fixed in html/xml report. 
Many cases we want to append testcase parameter as part of method name inside report.

The best solution so far is:
http://stackoverflow.com/questions/24642711/set-testng-test-name-as-seen-on-the-html-report-dynamically-from-the-dataprovi/37289372#37289372

But it has two problems:
1. It does not work for multi-threaded dataProvider(parallel=true)
2. It needs to use reflection which is hard to understand.

Please provide public API to support this.

Thanks,

Henry

**Comment by htzhang2** [comment]
Will you provide an example on how to change test method name from end user's view?

Let's say that we have a DataProvider method and a Test method:

How to customize test method name based on data provider parameter?

----------------
public testClass {
    @DataProvider(name = "MyProvider", parallel = true)
    public Object[][] MyTestProvider() throws Exception {
        List<MyTestCase> testList = new ArrayList<MyTestCase>();
        // generate testList from json file
       ...
        Object[][] caseList = new Object[testList.size()][1];
        // Populate test case parameter
        ...
        return caseList;
    }

   @Test(dataProvider = "MyProvider")
    public void test1(final MyTestCase testCase) {
     // How to change test method name ??
    // The default test method name is test1
    // We want test method name based on testCase parameter
    }
}

**Comment by krmahadevan** [comment]
@htzhang2 - Can you please take a look at this unit test [TestClassSample.java ](https://github.com/cbeust/testng/blob/master/src/test/java/test/name/github1046/TestClassSample.java) It should tell you how to get this done for your use-case.
