### ISSUE TITLE
Test skipped instead failed if incorrect enum value is passed as parameter in testNG xml

### ISSUE THREAD

**Issue by lizaivanova** [testng-team/testng#1105]
example:

``` java
@Parameters ("parameter")
public void testMethod(MyEnum parameter) {
...
}
```

testng.xml:

``` xml
<test name="...">
...
   <methods>
        <include name="testMethod">
              <parameter name="parameter" value="INVALID_VALUE" />
               .....
```
## Actual behavior:

in 6.9.\* test will be just skipped with no explanation and qa engineer can't find reason why
## Expected behavior: (as in versions 6.8 and earlier)

test fails with `java.lang.IllegalArgumentException: No enum constant...`

**Comment by juherr** [comment]
@cbeust Which behavior do you prefer?

**Comment by cbeust** [comment]
We should fail with `IllegalArgumentException`.

**Comment by juherr** [comment]
When you say "fail", you mean only change the test flag with an appropriate message, or crash the runner itself? 

Currently, the flag is "skip" and I don't know yet about the message.

**Comment by cbeust** [comment]
I think we should fail the test, not just skip it. It's clearly a developer
bug.


-- 
Cédric

**Comment by juherr** [comment]
Ok, we are agree. 
I asked details because I'm not sure it is the initial request.

**Comment by juherr** [comment]
@cbeust I fixed the issue but now https://github.com/cbeust/testng/blob/master/src/test/java/test/dataprovider/FailingDataProviderTest.java are failing because the test result change from skipped to failed.

I think `duplicateDataProviders` should fail because:

> It's clearly a developer bug.

But what about the 2 others?

**Comment by juherr** [comment]
Ping @cbeust

**Comment by cbeust** [comment]
I don't have any strong feeling either way, pick the behavior you think makes the most sense.
