### ISSUE TITLE
System rules [Feature request]

### ISSUE THREAD

**Issue by luengnat** [testng-team/testng#1172]
### TestNG Version

> Note: only the latest version is supported
> 6.9.11

It would be nice if TestNG could support something like System Rules in JUnit.
http://stefanbirkner.github.io/system-rules/

**Comment by juherr** [comment]
System rules should support TestNG instead: https://github.com/stefanbirkner/system-rules/issues/41

And a solution is using listeners: http://testng.org/doc/documentation-main.html#testng-listeners

**Comment by krmahadevan** [comment]
Relevant StackOverFlow thread with options : https://stackoverflow.com/questions/6099633/does-testng-support-something-like-junit4s-rule

A sample implementation https://github.com/wolfs/testng-rules
