### ISSUE TITLE
Suite of suite-files has CloseChannelException

### ISSUE THREAD

**Issue by james-crocker** [testng-team/testng#1201]
### TestNG Version

6.9.13
### Expected behavior

Successful read of a suite-file.
### Actual behavior

```
Caused by: org.testng.TestNGException: java.nio.channels.ClosedChannelException
    at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:20)
    at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
    at org.testng.xml.Parser.parse(Parser.java:170)
    at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:279)
    at org.testng.TestNG.run(TestNG.java:1081)
```
### Notes

Both files exist and readable. Running just tests.xml is successful. Running with individually enumerated suite xml eg. tests1.xml, tests2.xml executes successfully.

Encountered while using TestNG in a maven project and assigning the suite xml programmatically with `testNg.setXmlSuites(List<XmlSuite>);`

Also, built 6.9.13 (Ubuntu 16.04 x64). Successful build. Jar in testng/build/libs/testng-6.9.13.jar. However there is 'no main manifest attribute'; so couldn't just do java -jar testng-6.9.13.jar suite-files.xml.
### Is the issue reproductible on runner?
- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans
### Test case sample
# suite-files.xml

``` xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite" preserve-order="true">
  <suite-files>
    <suite-file path="/tmp/tests.xml"></suite-file>
  </suite-files>
</suite>
```
# tests.xml

``` xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="ParallelTests" preserve-order="true" parallel="tests">
  <test name="TestGoogle">
    <classes>
      <class name="com.sios.stc.coseng.tests.demo.Google">
        <methods>
          <include name="connect1" />
        </methods>
      </class>
    </classes>
  </test>
</suite>
```

**Comment by juherr** [comment]
> However there is 'no main manifest attribute'; so couldn't just do java -jar testng-6.9.13.jar suite-files.xml.

Related to https://github.com/cbeust/testng/issues/1190

**Comment by juherr** [comment]
@james-crocker I'm not able to reproduce the issue. Could you share a full runnable sample?

My test was and work as expected (minus #863):

```java
  @Test
  public void test() throws IOException, SAXException, ParserConfigurationException {
    TestNG tng = new TestNG();
    tng.setXmlSuites(new Parser("suite-files.xml").parseToList());
    tng.run();
  }
```

**Comment by james-crocker** [comment]
Went back to create a simple example. In doing so, found that during some pre-processing I set the xmlSuite.setFileName() which in turn made it self-referential I think. At any rate, removed this step and all is good in reading a suite xml file with suite-files declarations. Thank you for time and consideration.

**Comment by juherr** [comment]
Ok. If you think something is wrong with setFileName, feel free to open another issue.
