### ISSUE TITLE
Group parameter not applying on included <suite-files> using maven -Dgroups option

### ISSUE THREAD

**Issue by acikojevic** [testng-team/testng#1257]
This is closely linked with #589, #689, #937 

### TestNG Version
v6.9.13.6

### Expected behavior
Running master testng.xml which contains other included `<suite-files>`using maven-surefire-plugin with `-Dgroups=group1` option. I would expect that only tests from group1 will run, ignoring all tests which are not in group1.

### Actual behavior
Running master testng.xml which contains other included `<suite-files>`using maven-surefire-plugin with `-Dgroups=group1` options. All tests will run, no matter which group they belong to.

### Is the issue reproductible on runner?
- Maven

### Test case sample
If tests are contained in master testng.xml everything works fine, but if test are in included `<suite-files> `then groups option is ignored and all tests are ran.

**Comment by juherr** [comment]
Thanks for the report. We need to check how surefire is providing the group attribute but it could be an issue there.
If possible, could you try to run your test with the command line? http://testng.org/doc/documentation-main.html#running-testng

**Comment by acikojevic** [comment]
No problem, I ran tests with the command line and still got the same behavior, groups are ignored in included suite-files and applied if I use only master testng.xml. So this shouldn't be maven-surefire related issue, hope this helps.

**Comment by juherr** [comment]
What is the command you run?
I suppose extra configuration (cli or maven) replaces the configuration in the suite.
It may be the expected behavior.
@cbeust WDYT?

**Comment by acikojevic** [comment]
I ran my code with `java -classpath pathToClassesAndLibs  org.testng.TestNG mastertestng.xml -groups group1`, no extra config.

Assume I have mastertestng.xml which invokes invokedestng.xml (which contains test classes). If you run code above it will run all groups.
If you run `java -classpath pathToClassesAndLibs  org.testng.TestNG invokedtestng.xml -groups group1` it will run only tests which are in group1.

**Comment by cbeust** [comment]
If the description is accurate, it's not working as intended. Included
suites should behave exactly as if the content of these files was
copy/pasted into the main file.


-- 
Cédric
