### ISSUE TITLE
Classes in testNg xml within <classes></classes> tag running depending on tests orders but not class orders

### ISSUE THREAD

**Issue by slipwalker** [testng-team/testng#1309]
I have a TestNG file looks something like that:

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="My Suite" verbose="2"  parallel="tests" thread-count="10">

    <test name="Some Workflow Tests" parallel="none">
        <classes>
            <class name="com.somepackage.test.MyTests1"/>
            <class name="com.somepackage.test.MyTests2"/>
        </classes>
    </test>

</suite>
```
In each test class I have test methods marked with Test annotation, starting with priority 1 and so on. When the tests were running, it turned out that TestNG executed all the tests with priority 1, then 2, etc and even didn't respect order of the classes within `<classes></classes>` tag. In my case, it looked like that : test with priority 1 from MyTests1 class -> test with priority 1 from MyTests2 class -> test with priority 2 from MyTests1 class -> test with priority 2 from MyTests2 class, etc. Should it be all the tests from MyTests1 class, only then tests from MyTests2, shouldn't it? It seems something new that probably was introduced during fixing the issue #1156.

**Comment by juherr** [comment]
Do you have any other dependency?
Even if it should be `true`by defualt, did you try the `preserve-order="true"` attribute?
Even if it should not impact anything, could try the `group-by-instances="true"` attribute too?

**Comment by slipwalker** [comment]
No, I don't. Given TestNG file is very simple example where the issue can be easily reproduced. Test classes contain only two methods each without any dependency. 
I tried setting `preserve-order="true"` and `group-by-instances="true"`, but it wouldn't help me.

**Comment by juherr** [comment]
@slipwalker I've just tried your suite file on the master branch and it is working as expected without any modification.

Could you try with TestNG 6.10 and 6.10.1-SNAPSHOT (from https://oss.sonatype.org/content/repositories/snapshots/)?
If it is still failing, could you share a full project?

**Comment by slipwalker** [comment]
@juherr So, my test classes are very straightforward to eliminate possible impact of any dependency:

MyTests1 class: 

```
import org.testng.annotations.Test;

public class MyTests1 {

    @Test(priority = 1)
    public void test1() {
        System.out.println("test1 from " + getClass().getSimpleName() + " class");
    }

    @Test(priority = 2)
    public void test2() {
        System.out.println("test2 from " + getClass().getSimpleName() + " class");
    }
}

```

MyTests2 class:

```
import org.testng.annotations.Test;

public class MyTests2 {

    @Test(priority = 1)
    public void test3() {
        System.out.println("test3 from " + getClass().getSimpleName() + " class");
    }

    @Test(priority = 2)
    public void test4() {
        System.out.println("test4 from " + getClass().getSimpleName() + " class");
    }
}
```
I've got following output from different TestNG version:

6.10.1-SNAPSHOT version. Wrong tests order:

```
...
... TestNG 6.10.1-SNAPSHOT by Cédric Beust (cedric@beust.com)
...
test1 from MyTests1 class
test3 from MyTests2 class
test2 from MyTests1 class
test4 from MyTests2 class

===============================================
My Suite
Total tests run: 4, Failures: 0, Skips: 0
===============================================

```

6.10 version. Wrong tests order:

```
... TestNG 6.10 by Cédric Beust (cedric@beust.com)
...

[TestNG] Running:
[ThreadUtil] Starting executor timeOut:2147483647ms workers:1 threadPoolSize:10
test1 from MyTests1 class
test3 from MyTests2 class
test2 from MyTests1 class
test4 from MyTests2 class

===============================================
My Suite
Total tests run: 4, Failures: 0, Skips: 0
===============================================

```

6.9.8 version. Need to a bit change xml file - instead of  `parallel="none"` use  `parallel="false"`. Got correct tests order:

```
...
... TestNG 6.9.8 by Cédric Beust (cedric@beust.com)
...

[TestNG] Running:
[ThreadUtil] Starting executor timeOut:2147483647ms workers:1 threadPoolSize:10
test1 from MyTests1 class
test2 from MyTests1 class
test3 from MyTests2 class
test4 from MyTests2 class

===============================================
My Suite
Total tests run: 4, Failures: 0, Skips: 0
===============================================
```

**Comment by juherr** [comment]
Ok, I didn't catch the priority part at the first read. I will try on my side asap. Thanks for the sample!

**Comment by juherr** [comment]
Well, in fact, the order you are showing is the new expected one.
Now, there is a different priority on ordering features. In your case, `priority` is more important than `preserve-order` then `priority` is respected first.

As I know, `priority` is not scoped in a class and that's why TestNG uses it in the global context (@cbeust Could you confirm?).

**Comment by juherr** [comment]
BTW, the fix is pretty easy: use `dependsOnMethods` feature.

I really recommend using `dependsOnMethods` instead of `priority` when possible.

**Comment by slipwalker** [comment]
It is not very convenient solution for me (and for other folks I suppose too). In case `priority` your tests can continue running when some tests before failed. But in case `dependsOnMethods` your tests will be skipped if dependent from test failed (what if I would like to have them run?). Also, that puts a restriction on each test method to have `dependsOnMethods` when I wanna keep some test orders, but there could be many tests methods and it's boring stuff to add it on each one.

**Comment by juherr** [comment]
I agree that changes are always a pain but it is much more easy to explain test orders now: 

> Hierarchy on order features (from less important to more important): groupByInstance, preserveOrder, priority, dependsOnGroups, dependsOnMethods
https://github.com/cbeust/testng/blob/master/CHANGES.txt#L38

Again, you are right when you say that `priority` and `dependsOnMethods` don't have the same exact behavior but they are currently working as expected (I hope so!).

We can't swap `preserveOrder` and `priority` importance because it will break `priority` (`preserveOrder` is `true` by default).
In your specific case, a "priority on class" is missing.

@cbeust WDYT?

**Comment by cbeust** [comment]
@juherr is right, `@Priority` is global. As you point out, `dependsOnMethods` and `dependsOnGroups` should be the preferred way to order things within a class.
