### ISSUE TITLE
Order established by IMethodInterceptor not honored when running with parallel='instances'

### ISSUE THREAD

**Issue by rscott231** [testng-team/testng#1396]
### TestNG Version
> Note: only the latest version is supported
6.11

### Expected behavior
Test execution order established by custom `IMethodInterceptor` is honored regardless of parallel execution method.

### Actual behavior
Test execution order established by custom `IMethodInterceptor` is ignored when parallel execution is set to `parallel='instances'`. I believe there are two reasons for this:
* `InstanceOrderingMethodInterceptor` runs after my interceptor and its method `groupMethodsByInstance` uses `Maps.newHashMap()` to group methods by instance. `HashMap` doesn't guarantee ordering so whatever method order was established by my interceptor is potentially shuffled. However, the order of the test instances is preserved.
* Later `TestRunner.createInstanceBasedParallelWorkers` is called. It uses `Maps.newListMultiMap()` to group methods by their method instance. Once the methods are grouped, the map is iterated using the `entrySet()` method. This is destructive to the ordering created by my interceptor because `ListMultiMap` uses a `HashMap` as its underlying data structure. This could be solved by somehow passing `true` to the `ListMultiMap` constructor. Given that the construction currently happens in a factory method, there would be a little work to thread it through.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
1. Create an interceptor that specifies a test execution order. It could be something trivial like reversing the order of the methods passed in.
1. Create a suite with a few test classes that simply print the name of the test class.
1. Run the suite a few times and observe random execution order.

**Comment by rscot231** [comment]
I'm going to spend some time digging into the tests for TestNG today and see if I can write a failing test case. If so, I'll submit a pull request.

**Comment by juherr** [comment]
@rscot231 Any test cases will help to understand the issue :+1:

**Comment by rscot231** [comment]
@juherr Test case and fix added [here](https://github.com/cbeust/testng/pull/1397)
