### ISSUE TITLE
How to change test method names

### ISSUE THREAD

**Issue by Udit2** [testng-team/testng#1424]
Hi,

Is there a way to change the test method names of test cases not just test case name .I know that the test case name can be changed by implementing ITEST iterfac and implementing its method but thats not what I am looking.I looking to change the name of methods so that I can show my test reports with my custom name?

Please provide inputs ASAP.

Best Regards

**Comment by juherr** [comment]
Hi,

What is the reporter you are using?

> so that I can show my test reports with my custom name

The reporter is supposed to use the test case name (and not the name of the method), and the name of the method is not supposed to be changed.

**Comment by Udit2** [comment]
I am using default reporter provided by testng.

my <test> tag has many classes in it, it displays in the following format packagename.classname.methodname on jira, my final aim is to show the test method name as my custom name not the one I am provided by testing

**Comment by juherr** [comment]
As workarround, you can use your own reporter which will generate the output you expect: http://testng.org/doc/documentation-main.html#logging-reporters

**Comment by juherr** [comment]
@Udit2 Could you share a sample (a test class + output) of what you are expecting?

**Comment by krmahadevan** [comment]
Closing this issue since there's no response from the user.
