### ISSUE TITLE
@AfterMethod(alwaysRun = true) is not getting called if we have exception in @BeforeMethod

### ISSUE THREAD

**Issue by dipak-pawar** [testng-team/testng#1426]
### TestNG Version
> 6.11

### Expected behavior
`@afterMethod` is not called if test is throwing exception in `@beforeMethod`.

### Actual behavior
`@afterMethod` should be called if test is throwing exception in `@beforeMethod`.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
>

**Comment by juherr** [comment]
IMO it is not an issue: according to [the documentation](http://testng.org/doc/documentation-main.html#annotations), you have to set `alwaysRun = true` on the `@AfterMethod`.

> alwaysRun: For after methods (afterSuite, afterClass, ...): If set to true, this configuration method will be run even if one or more methods invoked previously failed or was skipped.

@cbeust WDYT?

**Comment by cbeust** [comment]
@juherr Agreed, not an issue.

**Comment by juherr** [comment]
But at the same time:

> configfailurepolicy: Whether TestNG should continue to execute the remaining tests in the suite or skip them if an @Before* method fails. Default behavior is skip.

BTW, `@AfterMethod` is not a test method but a configuration one.

**Comment by dipak-pawar** [comment]
@juherr @cbeust 
> IMO it is not an issue: according to the documentation, you have to set alwaysRun = true on the @AfterMethod.

I have added tests in #1432  for this issue which should be failed as this is bug in current version of testng.

Could you please look into it? Once you confirmed it. I'll provide fix for it.

**Comment by juherr** [comment]
I reopen because #1432 is showing the issue.

@dipak-pawar Thanks for the test case and the effort :)

**Comment by dipak-pawar** [comment]
@juherr Thank you for reopening this issue. I have provided fix in #1432. So tests should be passing now. Please have a look into it.

**Comment by juherr** [comment]
Fixed by #1432

**Comment by dipak-pawar** [comment]
@juherr Do you have any idea when do we get new release of testng?

**Comment by bartoszmajsak** [comment]
@juherr @cbeust Just wondering what are the plans for the next release, as without this fix we are not able to run TestNG tests (newer than 6.8.21) in Arquillian.

**Comment by juherr** [comment]
@bartoszmajsak There is no existing plan and the changelog looks big enough. I think @cbeust can make a release asap.

**Comment by bartoszmajsak** [comment]
That would be awesome @juherr. @cbeust do you plan to make a release anytime soon?

**Comment by bartoszmajsak** [comment]
Just noticed that `6.12` is out. Thanks!

**Comment by bartoszmajsak** [comment]
Sorry for being such a PITA, but can you give me some answer @cbeust @juherr? :)

**Comment by juherr** [comment]
Cédric has some issues with maven central and you can follow #1506

**Comment by bartoszmajsak** [comment]
Thanks! Haven't noticed this issue.
