### ISSUE TITLE
@Test annotated methods cannot inject java.lang.reflect.Method

### ISSUE THREAD

**Issue by steveprentice** [testng-team/testng#1649]
### TestNG Version
6.13.1, 6.12

### Expected behavior

java.lang.reflect.Method should be injectable into a `@Test` annotated method.

### Actual behavior

Starting with the 6.12 release, injection fails with:

> org.testng.TestNGException: 
> Cannot inject @Test annotated Method [withInjection] with [class java.lang.reflect.Method].
> For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```java
    @Test
    public void withInjection(Method m) {
        Assert.assertEquals(m.getName(), "withInjection");
    }
```

**Comment by krmahadevan** [comment]
@steveprentice - Thanks for the bug report.

I am not sure if I should call this behavior as a bug (or) **functionality tweaked**

Before TestNG 6.12, this was working and now it doesn't. In that perspective, yes its a bug. 

But this information is easily available to you via the `ITestResult` object of the current method. So IMO its redundancy to provide it via native injection as well.

Here's a sample that shows how it can be retrieved.

```java
    @Test
    public void anotherTestMethod() {
        ITestResult result = Reporter.getCurrentTestResult();
        System.err.println("Running " + result.getMethod().getConstructorOrMethod().getMethod().getName());
    }
```

Please refer to the wiki page for the complete mapping https://github.com/cbeust/testng/wiki/Allowed-parameters-injection-in-methods 

ping @juherr WDYT ?

**Comment by steveprentice** [comment]
The link provided in the error message from TestNG (http://testng.org/doc/documentation-main.html#native-dependency-injection) provides a nearly identical example that causes the issue as is referenced in this issue. The example implies that you can inject Method into a test method and that you can turn that off with the @NoInjection annotation which makes the Method value come from the provider instead. The example as written still works, but throws an odd warning. It only works because it heads down a different code path with the provider but still ends up successfully injecting the Method instance.

The functionality has definitely been tweaked from what has worked for a long time. We have thousands of these spread across a large code base coming from different teams and origins. Makes me think this usage might not be isolated to some of our tests and the example linked by the error message.

What was the reason for tweaking the functionality? Was it causing issues or was it an unintentional side-effect of refactoring the internal.Parameters class?

**Comment by juherr** [comment]
It's an issue we must fix.
It looks the test cases don't cover the feature enough.

Maybe it is a sideeffect of #1447 or #1459

**Comment by krmahadevan** [comment]
@juherr - I think the root cause of the problem is perhaps due to [this](https://github.com/cbeust/testng/commit/d0903b4fdcd72e04978f81db6c3b1b83eb18e9fc) commit wherein I added a mapping to facilitate the ease of producing proper error messages when improper native injection combinations were used.  I will get this fixed.

**Comment by juherr** [comment]
@krmahadevan Yes, maybe it is this commit.

**Comment by steveprentice** [comment]
Thanks, all!

**Comment by jiangty-addepar** [comment]
Hi, when will the next Maven release happen? We're running into this issue when we try to upgrade TestNG.

**Comment by cbeust** [comment]
Very soon. There is 6.14.0-RC1 on JCenter if you want to test with it.
