### ISSUE TITLE
@Ignore doesn't work when used on child class, and parent has @Test methods

### ISSUE THREAD

**Issue by krmahadevan** [testng-team/testng#1709]
### TestNG Version
> Note: only the latest version is supported
6.14.3

### Expected behavior
The inherited `@Test` methods from the base class should be ignored.

### Actual behavior
The inherited `@Test` methods from base class get executed.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Base class**

```java
import org.testng.annotations.Test;

public class ParentClassTest {
    @Test
    public void testc() {
        hook();
    }

    protected void hook() {};
}
```

**Child class**

```java
import org.testng.Reporter;
import org.testng.annotations.Ignore;

@Ignore
public class ChildClassTest extends ParentClassTest {
    @Override
    protected void hook() {
        Reporter.log("ChildClassTest#hook()");
    }
}
```

**Test Runner**

```java
import org.assertj.core.api.Assertions;
import org.testng.ITestNGListener;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.TestListenerAdapter;
import org.testng.TestNG;
import org.testng.annotations.Test;

public class IgnoreTestRunner {
    @Test
    public void testMethod() {
        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{ChildClassTest.class});
        TestListenerAdapter adapter = new TestListenerAdapter();
        testNG.addListener((ITestNGListener) adapter);
        testNG.run();
        ITestResult result = adapter.getPassedTests().get(0);
        Assertions.assertThat(Reporter.getOutput(result)).isEmpty();
    }
}
```

**Comment by krmahadevan** [comment]
My Analysis : 
TestNG makes use of an annotation transformer to get this done. But the problem with annotation transformers is, it passes you one of the following :

1. The test class (or)
2. The constructor (or)
3. The method object [ in this case this is what comes in]

TestNG should additionally somehow pass in the actual class where the method occurred to the annotation transformer as well.

i.e., we need to enhance `org.testng.internal.TestNGClassFinder#isTestNGClass` and pass `cls` as well.

This means that we would need to add a new signature to the interface `org.testng.internal.annotations.IAnnotationFinder` which looks like below 

`org.testng.internal.annotations.IAnnotationFinder#findAnnotation(java.lang.Class<?>, java.lang.reflect.Method, java.lang.Class<A>)`

wherein the first parameter of this method represents the actual class.

We then need to enhance `org.testng.internal.annotations.IAnnotationTransformer` and add a new method to it such as the one below 

```java
  public void transform(ITestAnnotation annotation, Class testClass,Constructor testConstructor, Method testMethod, Class<?> occurring clazz);
```

Currently we are on JDK7, so we can't really update the `org.testng.internal.annotations.IAnnotationFinder` interface without breaking backward compatibility (or can we ?)

@cbeust @juherr Do you think that there are use cases wherein we would have users outside of the TestNG codebase implementing `org.testng.internal.annotations.IAnnotationFinder` interface ? If not, I can update this interface. If there are users, then what are my alternatives ? Please let me know. I will try fixing this issue based on your suggestions.

**Comment by krmahadevan** [comment]
ping @cbeust @juherr what are your thoughts on the above proposed changes ? 

We could also consider moving to JDK8 and leverage default methods (I know what the answer would be.. :) but still fancying my chances... )

**Comment by juherr** [comment]
I can't imagine someone using a specific `IAnnotationFinder`. So, you can add a new method without problem.
At least, we will have less complains than if we drop java7 support ;)

About Java8, I propose to make the upgrade when the next Java LTS will be released (Java 11).

**Comment by slipwalker** [comment]
@krmahadevan , @juherr guys, would really appreciate to have it fixed and included in upcoming release.

**Comment by krmahadevan** [comment]
@slipwalker - Can you please share a sample that I can use to recreate the issue ?

**Comment by francoisprunier** [comment]
Hi @krmahadevan,

We're also experiencing this problem, the sample in the issue description is exactly what we use.

**Comment by krmahadevan** [comment]
@francoisprunier - I can't reproduce the issue. The `@Ignore` annotation does ignore methods properly.

Here's the same sample but with the assertions fixed properly.

```java
import org.testng.annotations.Test;

public class ParentClassTest {
  @Test
  public void testc() {
    hook();
  }

  protected void hook() {};
}
```

```java
import org.testng.Reporter;
import org.testng.annotations.Ignore;

@Ignore
public class ChildClassTest extends ParentClassTest {
  @Override
  protected void hook() {
    Reporter.log("ChildClassTest#hook()", true);
  }
}
```

```java
import org.assertj.core.api.Assertions;
import org.testng.TestListenerAdapter;
import org.testng.TestNG;
import org.testng.annotations.Test;

public class IgnoreTestRunner {
  @Test
  public void testMethod() {
    TestNG testNG = new TestNG();
    testNG.setTestClasses(new Class[]{ChildClassTest.class});
    TestListenerAdapter adapter = new TestListenerAdapter();
    testNG.addListener(adapter);
    testNG.setVerbose(2);
    testNG.run();
    Assertions.assertThat(adapter.getSkippedTests()).isEmpty();
    Assertions.assertThat(adapter.getPassedTests()).isEmpty();
    Assertions.assertThat(adapter.getFailedTests()).isEmpty();
  }
}
```

**Execution output**

```
===============================================
    Command line test
    Tests run: 0, Failures: 0, Skips: 0
===============================================


===============================================
Command line suite
Total tests run: 0, Passes: 0, Failures: 0, Skips: 0
===============================================

[TestNG] No tests found. Nothing was run
Usage: <main class> [options] The XML suite files to run
  Options:
    -alwaysrunlisteners
      Should MethodInvocation Listeners be run even for skipped methods
      Default: true
    -configfailurepolicy
      Configuration failure policy (skip or continue)
    -d
      Output directory
    -dataproviderthreadcount
      Number of threads to use when running data providers
    -excludegroups
      Comma-separated list of group names to  exclude
    -groups
      Comma-separated list of group names to be run
    -junit
      JUnit mode
      Default: false
    -listener
      List of .class files or list of class names implementing ITestListener 
      or ISuiteListener
    -methods
      Comma separated of test methods
      Default: []
    -methodselectors
      List of .class files or list of class names implementing IMethodSelector
    -mixed
      Mixed mode - autodetect the type of current test and run it with 
      appropriate runner
      Default: false
    -objectfactory
      List of .class files or list of class names implementing 
      ITestRunnerFactory 
    -parallel
      Parallel mode (methods, tests or classes)
      Possible Values: [tests, methods, classes, instances, none, true, false]
    -port
      The port
    -reporter
      Extended configuration for custom report listener
    -suitename
      Default name of test suite, if not specified in suite definition file or 
      source code
    -suitethreadpoolsize
      Size of the thread pool to use to run suites
      Default: 1
    -testclass
      The list of test classes
    -testjar
      A jar file containing the tests
    -testname
      Default name of test, if not specified in suitedefinition file or source 
      code 
    -testnames
      The list of test names to run
    -testrunfactory, -testRunFactory
      The factory used to create tests
    -threadcount
      Number of threads to use when running tests in parallel
    -usedefaultlisteners
      Whether to use the default listeners
      Default: true
    -log, -verbose
      Level of verbosity
    -xmlpathinjar
      The full path to the xml file inside the jar file (only valid if 
      -testjar was specified)
      Default: testng.xml


===============================================
Default Suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0

```

As you can see from the above output, there are no tests being executed. FWIW, I am using TestNG `7.0.0-beta3`. So please retry using this version and if the problem persists please help share a sample that can be used to reproduce the issue.

**Comment by francoisprunier** [comment]
Hello @krmahadevan,

I was able to reproduce with `7.0.0-beta3` by modifying the Child class as show below:

```
import org.testng.annotations.Test;

public class ParentClassTest {
  @Test
  public void testc() {
    hook();
  }

  @Test
  public void testa() {
    hook();
  }
  protected void hook() {};
}
```

Simply adding a second method ran 1 test instead of 0.
