### ISSUE TITLE
Need a way to exclude built-in interceptors from being added to alter method order

### ISSUE THREAD

**Issue by krmahadevan** [testng-team/testng#1726]
### TestNG Version
> Note: only the latest version is supported
6.14.3

### Expected behavior
The method order as determined by user provided method interceptor should be the order in which tests are executed.

### Actual behavior

The method order gets changed based on the outcome of the built-in interceptor that TestNG injects finally (Currently its either `org.testng.PreserveOrderMethodInterceptor` when `preserve-order=true` or `org.testng.InstanceOrderingMethodInterceptor` when `preserve-order=false`)

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Test classes**

```java
import org.testng.annotations.Test;
import priority.Priority;

public class TestClass1 {

    @Priority(4)
    @Test(description = "Test Multiple Day Absence Request flow", groups = "Test")
    public void Test1() {
        System.out.println(getClass().getName() + ".Test1");
    }

    @Priority(8)
    @Test(description = "Test Single Day Absence Request Flow", groups = {"Regression", "Test"})
    public void Test2() {
        System.out.println(getClass().getName() + ".Test2");
    }
}
```

```java
import org.testng.annotations.Test;
import priority.Priority;

public class TestClass2 {

    @Priority(3)
    @Test(description = "Test Multiple Day Absence Request flow", groups = "Test")
    public void Test3() {
        System.out.println(getClass().getName() + ".Test3");
    }

    @Priority(9)
    @Test(description = "Test Single Day Absence Request Flow", groups = {"Regression", "Test"})
    public void Test4() {
        System.out.println(getClass().getName() + ".Test4");
    }
}
```

Custom annotation looks like below:

```java
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

@Retention(java.lang.annotation.RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
public @interface Priority {
    int value() default 0;
}
```

Custom interceptor looks like below:

```java
import org.testng.IMethodInstance;
import org.testng.IMethodInterceptor;
import org.testng.ITestContext;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class PriorityInterceptor implements IMethodInterceptor {
    public static List<String> ordered = new ArrayList<>();

    public List<IMethodInstance> intercept(List<IMethodInstance> methods,
                                           ITestContext context) {
        Comparator<IMethodInstance> comparator = new Comparator<IMethodInstance>() {

            private int getPriority(IMethodInstance mi) {
                int result = 0;
                Method method = mi.getMethod().getConstructorOrMethod().getMethod();
                Priority a1 = method.getAnnotation(Priority.class);
                if (a1 != null) {
                    result = a1.value();
                } else {
                    Class<?> cls = method.getDeclaringClass();
                    Priority classPriority = cls.getAnnotation(Priority.class);
                    if (classPriority != null) {
                        result = classPriority.value();
                    }
                }
                return result;
            }

            public int compare(IMethodInstance m1, IMethodInstance m2) {
                return getPriority(m1) - getPriority(m2);
            }

        };
        methods.sort(comparator);
        methods.forEach(m -> {
            String clazz = m.getMethod().getInstance().getClass().getName() + ".";
            ordered.add(clazz + m.getMethod().getMethodName());
        });
        return methods;
    }

}
```

Here's how the test runner looks like

```java
import org.testng.Assert;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestNGListener;
import org.testng.ITestResult;
import org.testng.TestNG;
import org.testng.annotations.Test;
import priority.PriorityInterceptor;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class TestRunner {
    @Test
    public void testMethod() {
        TestNG testng = new TestNG();
        testng.setTestClasses(new Class[]{TestClass1.class, TestClass2.class});
        testng.addListener(new PriorityInterceptor());
        testng.addListener((ITestNGListener) new MethodOrderTracker());
        testng.run();
        List<String> expected = Arrays.asList(
                "scenarios.TestClass2.Test3",
                "scenarios.TestClass1.Test1",
                "scenarios.TestClass1.Test2",
                "scenarios.TestClass2.Test4"
        );
        Assert.assertEquals(MethodOrderTracker.ordered, expected);
    }

    public static class MethodOrderTracker implements IInvokedMethodListener {
        static List<String> ordered = new ArrayList<>();

        @Override
        public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {

        }

        @Override
        public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
            String clazz = method.getTestMethod().getRealClass().getName() + ".";
            ordered.add(clazz + method.getTestMethod().getMethodName());
        }
    }
}
```

Currently the test runner is failing.

**Comment by krmahadevan** [comment]
ping @cbeust @juherr - Need your inputs on this. Should we support a use case wherein we let users wire off the **in-built** interceptors if they choose to ?

This bug is being filed on behalf of the user as a result of [this](https://groups.google.com/forum/#!topic/testng-users/cSP4QpVGxMQ) google forum thread

**Comment by juherr** [comment]
Will it work if we insert the built-in interceptor at the first position instead of the end? https://github.com/cbeust/testng/blame/3b48a722e385bcbfdd1bc5f01babd394231a3de4/src/main/java/org/testng/TestRunner.java#L665

**Comment by krmahadevan** [comment]
@juherr - Not that I didn't consider that. But for me it was more of, what are we gaining by doing that. We are only going to be running one more method interceptor, unnecessarily without any use. That was why I was thinking that perhaps disabling it would be a better option. WDYT ?

**Comment by dwightdhooge** [comment]
Hi, I am the original reporter of the issue. 

With help of a testng xml file. I tried several combinations with preserve-order="true" or "false", but none was successful. Methods are ordered, but finally not executed in that order and stays grouped per class.  

I do have found a situation where it does works. 

I made a gradle project (https://bitbucket.org/dwightdhooge/gradletest) with testng code only. 
I dynamically create a testng file. The real cmd I finally want to use is `./Gradlew runTest -PtestGroup=Regression `. But this doesn't work yet.  

When I set : 
`test.setPreserveOrder(true);`
Then I have the following situations 

**Cmd: ./Gradlew runTest -PtestGroup=Regression**
 ==>  **Executed order is not Correct** 
scenarios.testClass1 -Test2
scenarios.testClass3 -Test5
scenarios.testClass3 -Test6
scenarios.testClass2 -Test4
scenarios.testClass2 -Test3

**Cmd:  ./Gradlew runTest -PtestClass1=testClass1 -PtestClass2=testClass2 -PtestClass3=testClass3 -PtestGroup=Regression**
  ==>  **Executed order is correct**
scenarios.testClass2 -Test4
scenarios.testClass3 -Test5
scenarios.testClass1 -Test2
scenarios.testClass2 -Test3
scenarios.testClass3 -Test6

**Cmd:  ./Gradlew runTest -PtestClass1=testClass1 -PtestClass2=testClass2 -PtestClass3=testClass3**
 ==>  **Executed order is correct** 
scenarios.testClass2 -Test4
scenarios.testClass3 -Test5
scenarios.testClass1 -Test1
scenarios.testClass1 -Test2
scenarios.testClass2 -Test3
scenarios.testClass3 -Test6

When 
`test.setPreserveOrder(false);`
the executed order is never okay and the tests stay grouped per class 

Examples: 
**Cmd:  ./Gradlew runTest -PtestClass1=testClass1 -PtestClass2=testClass2 -PtestClass3=testClass3 -PtestGroup=Regression**
  ==>  **Executed order is not Correct**  
scenarios.testClass2 -Test4
scenarios.testClass2 -Test3
scenarios.testClass3 -Test5
scenarios.testClass3 -Test6
scenarios.testClass1 -Test2

**Cmd:  ./Gradlew runTest -PtestClass1=testClass1 -PtestClass2=testClass2 -PtestClass3=testClass3
 ==>  Executed order is not Correct** 
scenarios.testClass2 -Test4
scenarios.testClass2 -Test3
scenarios.testClass3 -Test5
scenarios.testClass3 -Test6
scenarios.testClass1 -Test1
scenarios.testClass1 -Test2

**Cmd: ./Gradlew runTest -PtestGroup=Regression
 ==>  Executed order is not Correct** 
scenarios.testClass2 -Test4
scenarios.testClass2 -Test3
scenarios.testClass3 -Test5
scenarios.testClass3 -Test6
scenarios.testClass1 -Test2


Regards,
Dwight

**Comment by dwightdhooge** [comment]
I fixed my issue by instead of setting my package
``` 
final List<XmlPackage> packages = new ArrayList<>();
packages.add(new XmlPackage(TESTS_PACKAGE));
test.setPackages(packages);
```
Getting all the classes of my package and setting them instead 
             
```
String[] testClasses = PackageUtils.findClassesInPackage("scenarios", new ArrayList<String>(), new ArrayList<>());
for (String eachClass : testClasses) {
      myClasses.add(new XmlClass(eachClass));
}
test.setXmlClasses(myClasses);
```

So the issue seem to be that the methodinterceptor is not working when setting a package only

**Comment by krmahadevan** [comment]
@dwightdhooge - The sample that I had shared, if you noticed, you would see that it sets classes and not as packages. Either ways, I am raising a pull request for this one.

**Comment by dwightdhooge** [comment]
@krmahadevan  So I should raise another issue for my findings? Or maybe wait to see if your solution has any impact?

**Comment by krmahadevan** [comment]
@dwightdhooge - I would suggest that you please wait for my PR to get merged. You then try using the snapshot version to see if it works for you. If it doesn't we can create a new issue and take it up from there.
