### ISSUE TITLE
Guice TypeListeners not invoked in 6.9+

### ISSUE THREAD

**Issue by jstastny-cz** [testng-team/testng#1727]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Using \@Guice annotation it is possible to register listeners in a guice module. These listeners should be invoked by Guice based on the registered scope.

### Actual behavior
The listener's hear method is not being invoked in testng 6.9+, as opposed to 6.8 where that works.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```java
public class MyModule implements Module {
    public void configure(Binder binder) {
       binder.bindListener(Matchers.any(), new MyTypeListener());
}

public class MyTypeListener implements TypeListener {
    public <I> void hear(TypeLiteral<I> type, final TypeEncounter<I> encounter) {
        Class<?> clazz = type.getRawType();
        System.out.println("listening for "+clazz);
        throw new RuntimeException("the listener's hear method got actually invoked.");
    }
}
@Guice(modules=MyModule.class)
public class MyTest(){
    @Test
    public void test(){
        Assert.assertTrue(true);
    }
}
```

**Comment by jstastny-cz** [comment]
When the module registering a typelistener is invoked as a parent-module on my suite, then it works as expected.
The closest info I could find is in:
[Guice TypeListener not notified about the injected class Type](https://stackoverflow.com/questions/19587015/guice-typelistener-not-notified-about-the-injected-class-type)

**Comment by juherr** [comment]
Since 6.8.8 and #418, TestNG is using child injectors.
So The answer is in your question: https://stackoverflow.com/a/19671113/4234729

Can we consider the issue as fixed?

**Comment by jstastny-cz** [comment]
@juherr I'd rather call the issue 'explained'.
I believe there is still a limitation. When using surefire, is there any other way how to configure the parent-module other than creating testng.xml suite file?
As an example take the listeners, these can be set for a suite in surefire config: plugin/configuration/properties/property[@name=listener]. Is there such an option for parent module?

**Comment by krmahadevan** [comment]
@jstastny-cz - I believe you can inject listeners into surefire via configurations. So you can build an implementation of `IAlterSuiteListener` and have a parent module injected into it via the listener. Please see if [this](https://rationaleemotions.wordpress.com/2018/01/20/automatically-wire-in-a-parent-guice-module-into-your-testng-test/) blog post of mine helps add more clarity.

**Comment by jstastny-cz** [comment]
@krmahadevan Thanks for pointing me to your blog post. It helped me to overcome the limitation.
