### ISSUE TITLE
thread-count not followed for parallel="test" if some tests have parallel="method"

### ISSUE THREAD

**Issue by Amr1977** [testng-team/testng#1918]
TestNG version: 6.10

Given the following suite, note that it has thread-count in suite tag and it is running in parallel a set of tests where one of these tests is supposed to run some methods in parallel.

![image](https://user-images.githubusercontent.com/3415198/45333323-d5f1e100-b575-11e8-8065-95ee4910afb5.png)

### Expected behavior
Total thread count is expected to match user defined number, so that number of threads allocated to parallel methods increases if other serial tests finish earlier.

### Actual behavior
Due to parallel method parameter in the test element named "parallel-methods"  I found that actual thread count is  not equal to user-defined thread-count.

problem is if I limit number of threads for parallel methods by using another thread count parameter for it,  then i will not be able to get max utilization of resources if other threads terminated earlier.

### Is the issue reproductible on runner?

- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

**Comment by krmahadevan** [comment]
@Amr1977 - Can you please retry this using the latest released version of TestNG viz., `7.0.0-beta1`. If the problem still persists, please help share a sample standalone that can be used to reproduce this issue.

**Comment by krmahadevan** [comment]
Closing this issue since there's no response from the user.
