### ISSUE TITLE
Retry fail test generates inconsistent results in parallel tests mode

### ISSUE THREAD

**Issue by tarun3kumar** [testng-team/testng#1941]
### TestNG Version
7.0.0-beta1 (latest at time of writing this bug. I found same issue with older versions 5.** and 6.**)

### Expected behavior
Retry fail test provides inconsistent results when tests are run in parallel mode - 

### Actual behavior
Retry failed test count should remain same whether tests are run on parallel or non parallel mode
Original issue was discussed here - https://groups.google.com/forum/#!topic/testng-users/w-REFVZw4as

* Non parallel mode - 5 failed and 15 ignored (since each test is retried three times) :green_heart: 

![Non parallel mode
5 failed and 15 ignored (since each test is retried three times)](https://user-images.githubusercontent.com/948511/47774750-253ecd00-dcee-11e8-86d5-255b6dbb67d8.png)

* Parallel tests mode - 5 failed, 8 ignored (should have been 15) :broken_heart:  

![Parallel tests mode - 5 failed, 8 ignored (should have been 15) ](https://user-images.githubusercontent.com/948511/47774972-be6de380-dcee-11e8-8d64-7ed11669b92c.png)

* Parallel test mode - 5 failed, 5 ignored (should have been 15) :broken_heart: 

![Parallel test mode - 5 failed, 5 ignored (should have been 15)](https://user-images.githubusercontent.com/948511/47775159-3805d180-dcef-11e8-8170-7da781ef885a.png)

### Is the issue reproductible on runner?

- [x] IntelliJ
- [x] testng.xml

### Test case sample
[testng-sample.zip](https://github.com/cbeust/testng/files/2533337/testng-sample.zip)

**Comment by krmahadevan** [comment]
@tarun3kumar - I am not able to reproduce the problem.

I altered your project structure to look like below (I renamed to project name to `github-1941` for the sake of convenience )

```bash
✔ ~/temp/github-1941/src
15:55 $ tree .
.
└── test
    ├── java
    │   ├── TestClass.java
    │   ├── TestRetryAnalyzer.java
    │   └── TestRetryListener.java
    └── resources
        └── testng.xml

3 directories, 4 files
```

I found two dependencies of TestNG, one with a `compile` scope (which is the default scope) and one with `test` scope. I am guessing that your project was perhaps still using the old version of TestNG. 

Here's the complete pom file for reference.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>testng-sample</groupId>
    <artifactId>github-1941</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.0.0-beta1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <encoding>utf-8</encoding>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.9</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.9</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>src/test/resources/testng.xml</suiteXmlFile>
                    </suiteXmlFiles>
                    <properties>
                        <property>
                            <name>usedefaultlisteners</name>
                            <value>false</value>
                        </property>
                    </properties>
                </configuration>
            </plugin>
        </plugins>

    </build>
</project>
```

I ran this a couple of times and I wasn't able to reproduce the problem. Moreover the IntelliJ TestNG plugin is not owned by the TestNG team but by JetBrains. So the issue could even be with the plugin as well.

Can you please try once again to reproduce the issue on command line in one of the following ways

1. Using the surefire plugin (or)
2. Using the TestNG APIs via a `main()` method ?

**Comment by tarun3kumar** [comment]
Hi @krmahadevan 

Thanks for checking the issue. This time I made sure that I have only one testng dependency - `7.0.0-beta1`

I executed test using `mvn test` on command line. 

There are 15 skipped test on non parallel mode - 
`Tests run: 20, Failures: 5, Errors: 0, Skipped: 15` :green_heart:

But I get inconsistent skipped result on parallel tests mode. Some times 10 skipped test, some times 4 skipped tests-
`Tests run: 15, Failures: 5, Errors: 0, Skipped: 10` :broken_heart:
`Tests run: 9, Failures: 5, Errors: 0, Skipped: 4` :broken_heart: 
etc..

You mentioned -
>  I wasn't able to reproduce the problem

I hope your `testng.xml` is set with - 
`<suite name="Selenium Framework Test Suite" parallel="tests" verbose="1" thread-count="5">`
Did you get 15 skipped test consistently on `mvn test` ?

**Comment by krmahadevan** [comment]
@tarun3kumar 

Yes, I was using your suite xml only.

I was now able to reproduce this issue on the command line.

As part of https://github.com/cbeust/testng/pull/1781 TestNG has changed itself wherein the retry analyzer instance is now tied to a test method method and so doesn't need explicit resets etc.,

I think the problem perhaps lies in your retry analyzer. Here's a changed version of the same. Can you please try again using this one ? [ I have just removed the static `AtomicInteger` and just used a regular `int` ]

```java
public class TestRetryAnalyzer implements IRetryAnalyzer {

  private static final int MAX_RETRY_COUNT = 3;
  private int count = MAX_RETRY_COUNT;

  @Override
  public boolean retry(ITestResult result) {
    boolean retryAgain = false;
    if (count > 0) {
      System.out.println("Going to retry test case: " + result.getMethod() + ", " + ((
          (MAX_RETRY_COUNT - count) + 1)) + " out of " + MAX_RETRY_COUNT);
      retryAgain = true;
      --count;
    }
    return retryAgain;
  }
}
```

Now the output is consistently showing as 

```
Tests run: 20, Failures: 5, Errors: 0, Skipped: 15
```

Please try again and let me know.

**Comment by tarun3kumar** [comment]
@krmahadevan problem solved :)
