### ISSUE TITLE
Groups are being ignored using <suite-files>

### ISSUE THREAD

**Issue by luisandre69** [testng-team/testng#1966]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Groups being taken in consideration

### Actual behavior
Groups are being ignored

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X ] IntelliJ
- [ ] NetBeans

### Test case sample
<suite>
<groups>        
  <exclude name="test"/>
        </run>
    </groups>

    <suite-files>
        <suite-file path=tests.xml"></suite-file>
    </suite-files>
</suite>

**Comment by krmahadevan** [comment]
@luisandre69 - Please add more context to this issue. What you have added is not sufficient enough to debug the problem. Can you please help create a sample standalone project that we can use to reproduce the problem. Also can you please try your scenario once again using TestNG `7.0.0-beta1` ?

**Comment by luisandre69** [comment]
Yes, i should be able to test,

lets say i got 3 files
1 that is the java file with the test 
the same have groups that i use to filter

all the tests where running fine until i decide to use suite-files
i wanted to create a base template and change parameters and groups in test cases
create multiple test cases and pass it on

in tests.xml is just a list of the tests i want running

on the .xml file im running the actual test im using
<suite name = "test">
some parameters
<groups>
<run>
<exclude name = "test" />
</run>
</groups>

<suite-files>
    <suite-file path=tests.xml"></suite-file>
</suite-files>

</suite>


The test runs as expected
but the groups excluded from the test is not being taken in consideration while the test is executed

**Comment by luisandre69** [comment]
> @luisandre69 - Please add more context to this issue. What you have added is not sufficient enough to debug the problem. Can you please help create a sample standalone project that we can use to reproduce the problem. Also can you please try your scenario once again using TestNG `7.0.0-beta1` ?

Yes, i should be able to test,

lets say i got 3 files
1 that is the java file with the test 
the same have groups that i use to filter

all the tests where running fine until i decide to use suite-files
i wanted to create a base template and change parameters and groups in test cases
create multiple test cases and pass it on

in tests.xml is just a list of the tests i want running

on the .xml file im running the actual test im using
<suite name = "test">
some parameters
<groups>
<run>
<exclude name = "test" />
</run>
</groups>

<suite-files>
    <suite-file path=tests.xml"></suite-file>
</suite-files>

</suite>


The test runs as expected
but the groups excluded from the test is not being taken in consideration while the test is executed

**Comment by krmahadevan** [comment]
@luisandre69 - Thanks for adding more context. Please help attach a sample standalone project that we can use to reproduce the problem. That would help us investigate what is going wrong.

You haven't told us what version of TestNG you have been using.

So please also try this scenario using `TestNG 7.0.0-beta1` and let us know how it goes.

**Comment by luisandre69** [comment]
```
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
            <scope>test</scope>
        </dependency>
```

                    
```
{...}
 @Test(enabled = true, groups = {"abc"})
public void test01() { ...}

 @Test(enabled = true, groups = {"abcd","1234"})
public void test02() { ...}

 @Test(enabled = true, groups = {"1234","acdc"})
public void test03() { ...}
```

                     
```
{...}
 @Test(enabled = true, groups = {"abcd"})
public void test01() { ...}

 @Test(enabled = true, groups = {"abc","1234"})
public void test02() { ...}

 @Test(enabled = true, groups = {"1234","acdc"})
public void test03() { ...}
```

                    
```
{...}
 @Test(enabled = true, groups = {"abc"})
public void test01() { ...}

 @Test(enabled = true, groups = {"abc","1234"})
public void test02() { ...}

 @Test(enabled = true, groups = {"1234","acdc"})
public void test03() { ...}
```

                                
```
<suite name="test">
    <test name="test1">
        
        <classes>
            <class name="test01"/>
        </classes>
    </test>

    <test name="test2">
        <classes>
            <class name="test02"/>
        </classes>
    </test>

    <test name="test3">
        <classes>
            <class name="test03"/>
        </classes>
    </test>
</suite>
```
                                                
```
<suite name="test 2">
    <groups>
        <run>
            <exclude name="abc"/>
        </run>
    </groups>

    <suite-files>
        <suite-file path="test_sample.xml"></suite-file>
  </suite-files>

</suite>

```


Using the example above, the code does execute test01, test02 and test03 (its expected);
The groups are filtered on "test_sample2.xml" using groups (excluding "abc")
The same filter is not applied and the test execute all tests

Expected behaviour:
Test1 run 
test02;
test03;

test2 run
test01;
test03;

test3 run
test03;

Actual behaviour:

All the tests being run

**Comment by krmahadevan** [comment]
@luisandre69 - As I requested before, did you try running this using TestNG `7.0.0-beta1` ? Does the problem still exist in that ?
