### ISSUE TITLE
Missing @Ignore annotation

### ISSUE THREAD

**Issue by cdalexndr** [testng-team/testng#1997]
In current TestNG [documentation](https://testng.org/doc/documentation-main.html#ignore-tests) it states that I can use `@Ignore` annotation to ignore tests, but the annotation is missing as you can see from the [javadoc](https://jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/annotations/package-summary.html).

**Comment by juherr** [comment]
The correct link should be https://jitpack.io/com/github/cbeust/testng/master-SNAPSHOT/javadoc/org/testng/annotations/package-summary.html

**Comment by krmahadevan** [comment]
@cdalexndr - for some reason the java docs you shared are not the latest. Your IDE should always fetch the latest javadocs for local reference.

If you are looking for a web page for the same, please start here

http://www.javadoc.io/doc/org.testng/testng/7.0.0-beta1

**Comment by cdalexndr** [comment]
Note that the link to the javadoc is from testng [main site](https://testng.org/doc/index.html) (top bar).
It should be corrected to the latest release (that includes the `@Ignore` annotation) to be in sync with the documentation.

**Comment by krmahadevan** [comment]
ping @juherr - Any idea on how to get the TestNG site to refer to the latest java docs ?

**Comment by juherr** [comment]
jitpack changed. The new url must be https://javadoc.jitpack.io/com/github/cbeust/testng/master-SNAPSHOT/javadoc/
