### ISSUE TITLE
TestNG - configfailurepolicy=“continue” is not working for retried test

### ISSUE THREAD

**Issue by NallaSandeep** [testng-team/testng#2148]
### TestNG Version
7.0.0

### Expected behavior
As configfailurepolicy is configured as "continue", the failure in @AfterMethod shouldn't cause retried test to be skipped.

### Actual behavior
Though configfailurepolicy value is set as "continue", the failure in @AfterMethod is causing the the retried test to be skipped.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
testng.xml - At suite level, configfailurepolicy value is set as "continue"

	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
	<suite name="Suite" parallel="classes" thread-count="1"
		configfailurepolicy="continue">
		<test name="Front-End">
			<classes>
				<class
					name="com.tests.ExcepionAfterMethodTest">
				</class>
			</classes>
		</test>
	</suite>
   
Test: Throwing an exception in configuration (i.e., @AfterMethod) method to cause failure. And using RetryAnalyzer to retry the failed test.

    import org.testng.Assert;
    import org.testng.annotations.Test;
    
    public class ExcepionAfterMethodTest{
    
        @BeforeMethod(alwaysRun=true)
        public void beforeMethod() {
            System.out.println("Before Method");
        }
        
        @Test (alwaysRun=true, retryAnalyzer=RetryAnalyzer.class)
        public void method() {
            System.out.println("Method");
            Assert.assertTrue(false);
        }
    
        @Test (alwaysRun=true)
        public void method1() {
            System.out.println("Method1");
        }

        @AfterMethod(alwaysRun=true)
        public void afterMethod() throws Exception {
            System.out.println("After Method");
            throw new Exception();
        }
    }

RetryAnalyzer: Will retry once, if a failure occurs.

    import org.testng.IRetryAnalyzer;
    import org.testng.ITestResult;

    public class RetryAnalyzer implements IRetryAnalyzer {
    
        private int counter = 0;
        private int retryLimit = 1;
    
        @Override
        public boolean retry(ITestResult result) {
            if (counter < retryLimit) {
                counter++;
                return true;
            }
            return false;
        }
    }

Result: Because of failure in @AfterMethod, the test is retried, but the @Test  is skipped. Hence, 'Method' is not printed in the result at the 5th line.

```
Before Method
Method
After Method
Before Method
After Method
Method1
After Method
```

Expected Result: As configfailurepolicy is configured as "continue", the retried test shouldn't be skipped. So, expecting 'Method' should be printed in the result at the 5th line as below.

```
Before Method
Method
After Method
Before Method
Method
After Method
Method1
After Method
```

**Comment by krmahadevan** [comment]
@NallaSandeep - I believe `configfailurepolicy` is only applicable for `@BeforeXXX` methods and not for `@AfterXXX` methods.

Quoting the documentation from [here](https://testng.org/doc/documentation-main.html#running-testng)

> Whether TestNG should continue to execute the remaining tests in the suite or skip them if an `@Before*` method fails. Default behavior is skip.

The documentation on the DTD from [here](https://github.com/cbeust/testng/blob/3b6cd4b94069e67126076e60212f9c3a212e8bdd/src/main/resources/testng-1.0.dtd#L47-L48) says the following

> `@attr`  configfailurepolicy  Whether to continue attempting Before/AfterClass/Methods after they've failed once or just skip remaining.

So request you to do two things

1. Can you find out if this ever worked before in any previous versions ? That way we would know if we broke something or if this was never working and then proceed accordingly.
2. check what happens when you introduce failures in other `@AfterXXX` methods and report back.

**Comment by NallaSandeep** [comment]
@krmahadevan, 
configfailurepolicy is working well for @AfterXXX methods **without RetryAnalyzer**. But, the issue is happening when we use RetryAnalyzer only.
1. I have checked with 6.14.3, 6.13.1, 6.11 versions. It's not working.
2. No issues when introducing failures in other @AfterXXX methods.

**Comment by NallaSandeep** [comment]
@krmahadevan,
Have you got chance to look into this, again?

**Comment by NallaSandeep** [comment]
@krmahadevan What version of TestNG this fix would be available with?

**Comment by NallaSandeep** [comment]
I see the fix is available with 7.1.0 version. Thanks.

**Comment by Proryanator** [comment]
Is there a way to set the configfailurepolicy _without_ having a suite file?

We removed the suite file long back for our project since it caused us to have to add in a test every time we made a new one, or remember to modify it if it gets re-named, etc.

Would love to know if there's some way to modify/adjust this property from a method listener or something.

**Comment by krmahadevan** [comment]
@Proryanator - You can do one of the following:

1. If you are using the maven-surefire plugin, then you can pass this as a property

```xml
<configuration>
	<properties>
		<property>
			<name>configfailurepolicy</name>
			<value>continue</value>
		</property>
	</properties>
</configuration>

```

2. The other option is to basically build an implementation of `org.testng.IAlterSuiteListener` and then wire in via service loading mechanism as detailed [here](https://testng.org/doc/documentation-main.html#listeners-service-loader)
