### ISSUE TITLE
Repository "About" section uses HTTP link

### ISSUE THREAD

**Issue by Marcono1234** [testng-team/testng#2515]
The "About" section of this GitHub repository, and https://github.com/testng-team/testng-team.github.io as well, uses an HTTP link to http://testng.org; it would be good to use an HTTPS link instead.

- https://github.com/cbeust/testng 
![About section screenshot](https://user-images.githubusercontent.com/11685886/113770214-29267300-9722-11eb-8886-c976133a34df.png)
- https://github.com/testng-team/testng-team.github.io
![About section screenshot](https://user-images.githubusercontent.com/11685886/113770259-36436200-9722-11eb-9fd9-82c59c8928e9.png)
- https://github.com/testng-team
![Organization screenshot](https://user-images.githubusercontent.com/11685886/113770475-7571b300-9722-11eb-8844-0fe3fdfb3785.png)

**Comment by juherr** [comment]
Fixed on testng-team/testng-team.github.io and organization.

@cbeust I don't have enough rights to fix it here.

**Comment by cbeust** [comment]
You don't have enough rights to fix where, @juherr ?

**Comment by Marcono1234** [comment]
He probably means this repository here (https://github.com/cbeust/testng). At the top right corner of the repository there is an "About" section using an HTTP link to testng.org (see screenshots above). Could you please change that to HTTPS?

**Comment by juherr** [comment]
Yes, I think I need to be an admin of the repository if I want to update the URL in the description.

**Comment by krmahadevan** [comment]
This is now fixed
