### ISSUE TITLE
Testng xml file is not honouring the preserve-order to true.

### ISSUE THREAD

**Issue by pras120687** [testng-team/testng#2583]
TestNG Version: 7.4.0

### Expected behavior
I have designed my testng xml file as below - 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="FABS BAT AUTOMATION TESTS" preserve-order="true" parallel="false">

    <listeners>
        <listener class-name="com.oracle.framework.TestListener" />
    </listeners>

    <test name="FABS BAT AUTOMATION TESTS" enabled="true" preserve-order="true">
        <parameter name="browser" value="chrome" />
        <parameter name="csv" value="" />

        <classes>
        <class name="oracle.fabs.NextGenTests.ProjectConfigurationTest_NG"></class>
       <class name="oracle.fabs.NextGenTests.LRGResultsAnalysis"></class> 
       <class name="oracle.fabs.NextGenTests.CompilationPreflightValidations"></class>
       <class name="oracle.fabs.NextGenTests.NextGen_BuildResults_FABT"></class> 
        <class name="oracle.fabs.NextGenTests.NextGen_BuildResults"></class>
        <class name="oracle.fabs.NextGenTests.ProjectDetailsTest"></class>
        <class name="com.oracle.test.LCMPrerequisite">
</classes>
    </test>
</suite>

but when i run it from eclipse it is maintaining order everytime. But when i run from linux through selenium grid it is not maintaining the preserve-order.

This issue is coming when i execute from linux box using selenium grid.

But this is working fine in eclipse.

**Comment by juherr** [comment]
Hi,

How can we reproduce the issue?

**Comment by pras120687** [comment]
To reproduce:
1. Create one testng xml file like above with preserve-order to true for classes
2. Then implement selenium grid
3. Run the testng xml from jenkins in linux vm
In that case it is not honouring the order

**Comment by juherr** [comment]
Could you provide a short sample and the way to run it?

**Comment by krmahadevan** [comment]
There has been no answer from the user. Closing this issue.
