### ISSUE TITLE
Disable test class

### ISSUE THREAD

**Issue by cdalexndr** [testng-team/testng#2603]
### TestNG Version
7.3.0

### Expected behavior
Ignore this class tests.

### Actual behavior
Running suite runs this class tests.

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```
@Test(enabled = false)
public class MyTestClass{
    @Test
    public void testMethod() {...}
}
```

**Comment by juherr** [comment]
Hi,

It is the expected behavior: the `enabled` value from the class is overridden by the value from the method (`true` by default).

You can use `@Ignore` instead.

**Comment by cdalexndr** [comment]
Then why `@Test` annotation has `@Target TYPE` so it's allowed on classes, even if `enabled` is overwritten, thus useless?
In my opinion, allowing `@Test` on class should overwrite `@Test` params of that class methods, include `enabled`.

**Comment by juherr** [comment]
See #151
