### ISSUE TITLE
A failed retry with ITestContext  will lose the ITestContext

### ISSUE THREAD

**Issue by renyiwei-xinyi** [testng-team/testng#2669]
### TestNG Version
> Note: 7.4.0

### Expected behavior
The example will be executed three times

异常抛出：
java.lang.AssertionError: 
Expected :1
Actual   :2

### Actual behavior
`java.lang.IllegalArgumentException: wrong number of arguments`

Found that the ITestContext context parameter is missing during debugging

### Is the issue reproducible on runner?
all
- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="test" parallel="false">
    <parameter name="id" value="1111"/>
    <parameter name="name" value="qa"/>
    <parameter name="age" value="30"/>

    <listeners>
        <!--rerun after failure-->
        <listener class-name="com.xxxx.xxxx.FailedRetryListener"/>
    </listeners>

    <test verbose="1" name="case1" thread-count="1">
        <classes>
            <class name="com.xxxx.xxx.xxxTest">
                <methods>
                    <include name="create"/>
                </methods>
            </class>
        </classes>
    </test>
</suite>
```

```java
@Parameters({"id", "name", "age"})
@Test(retryAnalyzer= FailedRetry.class)
public void create(String id, String name, String age, ITestContext context){
    Assert.assertEquels(1,2)
}
```

```java
public class FailedRetry implements IRetryAnalyzer {
    private int retryCount = 1;
    private static final int maxRetryCount = 3;

    @Override
    public boolean retry(ITestResult iTestResult) {
        //If an exception is thrown, the failure case will be rerun. If it is an assertion error, try again
        if (iTestResult.getThrowable() instanceof AssertionError && retryCount % maxRetryCount != 0) {
            retryCount++;
            return true;
        } else {
            retryCount = 1;
            return false;
        }
    }
}
```

```java
public class FailedRetryListener implements IAnnotationTransformer {

    @Override
    public void transform(ITestAnnotation iTestAnnotation, Class aClass,
                          Constructor constructor, Method method) {
        {
            IRetryAnalyzer retry = null;
            try {
                retry = iTestAnnotation.getRetryAnalyzerClass().newInstance();
            } catch (InstantiationException | IllegalAccessException e) {
                e.printStackTrace();
            }
            if (retry == null) {
                iTestAnnotation.setRetryAnalyzer(FailedRetry.class);
            }
        }
    }
}
```

**Comment by renyiwei-xinyi** [comment]
> ### TestNG Version
> > Note: 7.4.0
> 
> ### Expected behavior
> The example will be executed three times
> 
> 异常抛出： java.lang.AssertionError: Expected :1 Actual :2
> 
> ### Actual behavior
> `java.lang.IllegalArgumentException: wrong number of arguments`
> 
> Found that the ITestContext context parameter is missing during debugging
> 
> ### Is the issue reproducible on runner?
> all
> 
> * [ ]  Shell
> * [√] Maven
> * [ ]  Gradle
> * [ ]  Ant
> * [ ]  Eclipse
> * [√] IntelliJ
> * [ ]  NetBeans
> 
> ### Test case sample
> > Please, share the test case (as small as possible) which shows the issue
> 
> `
> 
> ```
> <listeners>
>     
>     <listener class-name="com.xxxx.xxxx.FailedRetryListener"/>
> </listeners>
> 
> <test verbose="1" name="case1" thread-count="1">
>     <classes>
>         <class name="com.xxxx.xxx.xxxTest">
>             <methods>
>                 <include name="create"/>
>             </methods>
>         </class>
>     </classes>
> </test>
> ```
> 
> `
> 
> `@Parameters({"id", "name", "age"}) @Test(retryAnalyzer= FailedRetry.class) public void create(String id, String name, String age, ITestContext context){ Assert.assertEquels(1,2) }`
> 
> `public class FailedRetry implements IRetryAnalyzer { private int retryCount = 1; private static final int maxRetryCount = 3;
> 
> ```
> @Override
> public boolean retry(ITestResult iTestResult) {
>     //If an exception is thrown, the failure case will be rerun. If it is an assertion error, try again
>     if (iTestResult.getThrowable() instanceof AssertionError && retryCount % maxRetryCount != 0) {
>         retryCount++;
>         return true;
>     } else {
>         retryCount = 1;
>         return false;
>     }
> }
> ```
> 
> } `
> 
> `public class FailedRetryListener implements IAnnotationTransformer {
> 
> ```
> @Override
> public void transform(ITestAnnotation iTestAnnotation, Class aClass,
>                       Constructor constructor, Method method) {
>     {
>         IRetryAnalyzer retry = null;
>         try {
>             retry = iTestAnnotation.getRetryAnalyzerClass().newInstance();
>         } catch (InstantiationException | IllegalAccessException e) {
>             e.printStackTrace();
>         }
>         if (retry == null) {
>             iTestAnnotation.setRetryAnalyzer(FailedRetry.class);
>         }
>     }
> }
> ```
> 
> }`

**Comment by juherr** [comment]
Please, could you provide the full stacktrace?

**Comment by krmahadevan** [comment]
@renyiwei-xinyi - Also please include the testng version that was used to trigger this problem.

**Comment by bj-9527** [comment]
From the test code, I think the root cause should be `public void create(String id, String name, String age, ITestContext context)`, the context is not matched here. TestNG only recognized 3 parameters, not 4.
In normal way, 
```
@Test
  public void test(ITestContext context) {
    System.out.println("do nothing" + context.getName());
  }
```
the context can be recognized. So do you think TestNG should support this or it's kind of bug

**Comment by juherr** [comment]
@bj-9527 it looks like an issue. I suppose the retry runner is not using the same code than the standard method runner
