### ISSUE TITLE
Testnames not working together with suites in suite

### ISSUE THREAD

**Issue by martinaldrin** [testng-team/testng#2709]
Hi,

I did a uplift yesterday and today many loops started to fail due missing functionality from our own fork. 
Feature was supposed to be included in TestNg in this commit, but something has changed since this commit was merged.
https://github.com/cbeust/testng/commit/3e14c7db6be71f76d4d630fcd162a8b3c8e566c6

07:12:50.792 [main] ERROR org.testng.TestNG - 
The test(s) <[test1,test2,test3]> cannot be found.

### TestNG Version
broken in  TestNg 7.5 works in 7.4
#2532 breaks the testname support for suites in suite

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
I will try to reproduce the fault in a small test, updates are coming.

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by martinaldrin** [comment]
Relates to this commit
https://github.com/cbeust/testng/pull/1635

**Comment by martinaldrin** [comment]
It looks like [#2532](https://github.com/cbeust/testng/pull/2619/commits/687903cc9308595597c42baae61c074c2ee664e9) is the root cause for this issue. Support for suites in suite together with testnames are broken from this commit.

**Comment by martinaldrin** [comment]
PullRequest is created to solve the issue

**Comment by krmahadevan** [comment]
@martinaldrin - Can you please help edit this issue and add some context around what is the use case wherein this bug is being seen? That would help us backtrack to the issue in the future if needed from the PR/commit.
