### ISSUE TITLE
IAnnotationTransformer causes org.testng.annotations.Ignore annotation to be ignored/overridden 

### ISSUE THREAD

**Issue by ecramer89** [testng-team/testng#2836]
### TestNG Version
> Note: only the latest version is supported
7.3.0

### Expected behavior
- Adding an IAnnotationTransformer listener to my test suite should not impact the @Ignore annotation on my tests. 

### Actual behavior
- Regardless of the body of the overridden transform method, if I add an IAnnotationTransformer to the listeners of my TestNG suite then tests with have the @Ignore annotation are executed (i.e. I was able to replicate this even when I commented out the entirety of the body of the transform method. Otherwise the transform method only sets the "enabled" flag to "false' for test methods that meet a condition). Nothing in the body of the method explicitly looked at/modified the @Ignore annotation. 

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```java
@Test
@Ignore
public void dummyTest(Method method) throws Throwable {
System.out.println("Dummy test executed");
}
```

```java
public class DummyTransformer implements IAnnotationTransformer {
@Override
    public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
System.out.println("Do nothing");
}
}
```

when I run the suite, I expect that dummyTest will not run and the line "Dummy test executed" will not appear on the terminal. However, the line does appear on the terminal. If I remove DummyTransformer from the listeners array in the gradle test run configuration, dummyTest does not run. Indicating that it is attributable to the presence of the IAnnotationTransformer.

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
@ecramer89 - Please retry using the latest TestNG version (`7.6.1` and needs JDK11) and see if the issue is reproducible

If the issue persists, attach a sample gradle project that can be used to debug.
