### ISSUE TITLE
Docs: invalid sample with outdated parameters

### ISSUE THREAD

**Issue by dr29bart** [testng-team/testng#2871]
https://testng.org/doc/documentation-main.html#running-testng
There is a note in the end of section 4
> Important: The command line flags that specify what tests should be run will be ignored if you also specify a testng.xml file, with the exception of -includedgroups and -excludedgroups, which will override all the group inclusions/exclusions found in testng.xml.

1. -includedgroups is supposed to be -groups 
2. It looks like there is an extra 'd' in -exclude**d**groups. The valid name is -excludegroups. Renamed by accident? [diff](https://github.com/cbeust/testng/commit/55cd8fe791efec01c80a0199de9d187d2c836801#diff-fea42656036c14b9c17dad40f9b89127064406a14368b333d74d920a1997f5f8R25) 

![image](https://user-images.githubusercontent.com/1547167/215567436-3c4200ec-a4f3-4016-9c19-c6d455bffbe2.png)

**Comment by RishabhSpark** [comment]
I will like to work on this
