### ISSUE TITLE
How to obtain Guice Injector in listeners?

### ISSUE THREAD

**Issue by groov1kk** [testng-team/testng#2890]
Hello

I noticed that you've removed methods from ```ITestContext``` that were able to retrieve an instance of ```Injector``` that was used in tests, such as ```getInjector(IClass iClass)```. I wonder, is there a way to extract an existing instance of injector in TestNG listeners in the current version (7.7.1) without these methods?

If so, could you please update a documentation?

**Comment by krmahadevan** [comment]
@groov1kk - Can you please try `org.testng.ITestContext#getInjectorFactory` and then use `org.testng.IInjectorFactory#getInjector(com.google.inject.Injector, com.google.inject.Stage, com.google.inject.Module...)` from the `IInjectorFactory` reference and see if that helps ? You should be able to grab hold of the `ITestContext` in the listeners.

**Comment by groov1kk** [comment]
@krmahadevan Thanks for the fast reply :) 

The problem that the method ```org.testng.ITestContext#getInjectorFactory and then use org.testng.IInjectorFactory#getInjector(com.google.inject.Injector, com.google.inject.Stage, com.google.inject.Module...)``` creates a new child injector instead of returning the existing one. And all singletons, for example, would be created again. Is there a way to return exactly the same instance of Injector?

**Comment by krmahadevan** [comment]
@groov1kk How about `org.testng.ISuite#getParentInjector` ?

**Comment by groov1kk** [comment]
Still there are two injectors in my test.

Here the simple example:

Guice module:

```java
public class MyModule extends AbstractModule {

  @Provides
  static MySingleton mySingleton() {
    return new MySingleton();
  }

  @Singleton
  public static class MySingleton {

    public void printHashCode() {
      System.out.println(hashCode());
    }
  }
}
```
Test:

```java
@Listeners(MyListener.class)
@Guice(modules = MyModule.class)
public class MyTest {

  @Inject private MySingleton singleton;

  @Test
  public void testSingleton() {
    singleton.printHashCode();
  }
}
```
Listener

```java
public class MyListener extends TestListenerAdapter {

  @Override
  public void onStart(ITestContext context) {
    Injector injector = context.getSuite().getParentInjector();
    injector.getInstance(MySingleton.class).printHashCode();
  }

  @Override
  public void onFinish(ITestContext context) {
    Injector injector = context.getSuite().getParentInjector();
    injector.getInstance(MySingleton.class).printHashCode();
  }
}
```

Every time I start this example, I see the following picture:
```
288958772
2106592975
288958772
```
Looks like I have one Injector for my test and another Injector in the listener.

**Comment by groov1kk** [comment]
Ah, I see...

That's because you create default parent Injector without any modules and Injector's ```getInstance``` puts the value if it has not been stored yet.

Also I see, that you have cache ```GuiceHelper#m_injectors``` but you don't expose it outside. I'm afraid without exposing it is not possible to obtain an instance of Injector in Listeners.

**Comment by krmahadevan** [comment]
@groov1kk - Thanks for the sample. I will get to it when I get some time. In the meantime, please feel free to propose a PR if you managed to find something

**Comment by juherr** [comment]
@groov1kk In order to propose the best solution, could you describe why you need injector in the listener? What are you trying to do?

**Comment by juherr** [comment]
For the record: Injector is removed from the public api because it is a strong dependency to guice.

**Comment by groov1kk** [comment]
@juherr There might be a lot of examples when do I need injector in listeners.

Let's say I have an HTTP client which is singleton and managed by guice. And I would like to send a request to a bug tracking system after each test with it's results. Or I would like to send an email after each test failed. The mail service is also better to setup and control by guice.

About strong dependency to guice: you've already have the annotation ```@Guice```, isn't it a strong dependency too? Or you are also going to replace it?

**Comment by juherr** [comment]
`@Guice` could be provided as an extension.  It is not the same kind of dependency.

About the listener need: what if `@Inject` is supported into listeners?

**Comment by groov1kk** [comment]
It would be cool :thumbsup:

**Comment by krmahadevan** [comment]
@groov1kk - Here's a sample that injects a value into a TestNG listener. I am using TestNG `v7.8.0`

```java
import com.google.inject.*;
import com.google.inject.Module;
import com.google.inject.name.Named;
import com.google.inject.name.Names;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestResult;
import org.testng.annotations.Guice;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(TestClassSample.MyListener.class)
public class TestClassSample {

    @Test
    public void testMethod() {
        System.err.println("testMethod() says Hello World");
    }

    @Guice(modules = GuiceExampleModule.class)
    public static class MyListener implements IInvokedMethodListener {

        @Named("port-number")
        @Inject
        Integer integer;

        @Override
        public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
            System.err.println("Port Number = " + integer);
        }
    }

    public static class GuiceExampleModule implements Module {
        @Override
        public void configure(Binder binder) {
            binder.bind(Integer.class)
                    .annotatedWith(Names.named("port-number"))
                    .toInstance(8080);
        }
    }
}
```

**Output:**

```bash
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Hello World
Port Number = 8080

===============================================
Default Suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================
```

Please let me know if this would solve your purpose and if yes, can we close this issue?

**Comment by groov1kk** [comment]
Hello @krmahadevan 

Thanks that you didn't forget about me :)

I check your solution and it works for, thank you!

P.S. Btw, last time I gave you a wrong example: to provide a singleton in Guice it is neccissary to mark the provider method with both annotations `@Provides` and `@Singleton`.  But anyway, even correctly written module didn't solve my problem.

**Comment by krmahadevan** [comment]
@groov1kk 

> Thanks that you didn't forget about me

Please bear with the lags in response. 

> I check your solution and it works for, thank you!

So can we close this issue ?

**Comment by groov1kk** [comment]
Yep, you could close this issue
