### ISSUE TITLE
RetryAnalyzer with custom retry counts coming from the dataprovider

### ISSUE THREAD

**Issue by PPdbamji** [testng-team/testng#2896]
### Expected behavior
We have a variable test data count for each test in our file. Each dataprovider may return a different number of testcases. We want to be able to pass down these testcase numbers to the retryAnalyzerImplementation class, such that each testcase is run for the desired max number.

### Actual behavior
The count of retries updates for all testcases instead of an individual testcase. eg. if we have 7 testcases with maxRetry as 3 and all tests fail, only 3 of the tests get retried instead of all testcases running 3 times.

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
Test 1 has a list of 7 testcases. We want to pass 35 (7 x 5) as the MaxRetry count. i.e each of the 7 testcases are retried 5 times on a failure.
Test 2 has a list of 3 testcases. We want to pass 15 (3 x 5) as the MaxRetry count. i.e each of the 3 testcases are retried 5 times on a failure.

**Comment by krmahadevan** [comment]
@PPdbamji can you please share a sample which shows what you are trying to do?

**Comment by PPdbamji** [comment]
@krmahadevan 

class TestFile{

dataProviderFunction named 'dataProviderData' returns a list of 2 items. 
eg [["fnam","lname",3], ["fname2","lname2",4]]

@Test(dataProvider = "dataProviderData", retryAnalyzer=ClassForRetry.class)
testname(TestDataFromDataProvider data){
// foobar
}

dataProviderFunction named 'dataProviderData2' returns a list of 3 items. 
eg [["fnam","lname",3], ["fname2","lname2",4], ["fname","lname",15]]

@Test(dataProvider = "dataProviderData2",retryAnalyzer=ClassForRetry.class)
testname2(TestDataFromDataProvider2 data){
// foobar
}
}

maxRetries in ClassForRetry is set to 5

test method Testname should have 10 retries (2 x 5) if all tests fail.
test method Testname2 should fail 15 times (3 x 5) if all tests fail. If only 2 of the test cases fail (eg. ["fname2","lname2",4], ["fname","lname",15]) then testcase ["fname2","lname2",4] should run 5 times and testcase ["fname","lname",15] should run 5 times.

**Comment by krmahadevan** [comment]
@PPdbamji - It still is not clear as to what the problem is. The retry count is defined by you in your `RetryAnalyzer` implementation. If a test method fails, then it would get retried to the max count as defined by your retry analyzer. The latest released version of TestNG `7.7.1` ensures that it uses a new instance of the retry analyzer per data provider iteration.
So its still NOT clear as to what the problem is.

Please help create a sample project that uses TestNG `7.7.1` and which can be used to reproduce the problem.

**Comment by krmahadevan** [comment]
Closing this issue since there's no response from the user.
