### ISSUE TITLE
Add location of docs Github to readme and contributions page

### ISSUE THREAD

**Issue by Kris-Martin** [testng-team/testng#2904]
Hi,

I think it would be helpful to add a link to the Github for the docs website in the testng readme and the testng contributions page so that people can more easily contribute to updating the docs website - assuming you would like to encourage people to do that.

[testNG docs website](https://github.com/testng-team/testng-team.github.io)

**Comment by juherr** [comment]
👍

Could you propose a pull request to fix that?

**Comment by mohsinsackeer** [comment]
#2946
I have created a pull request for this. Please check it out.
