### ISSUE TITLE
Cannot use listener implementing all TestNG Listeners

### ISSUE THREAD

**Issue by harmin-parra** [testng-team/testng#2911]
### TestNG Version
7.8.0

### Expected behavior
I can declare and use a class implementing TestNG Listeners (IReporter, ISuiteListener, ITestListener, IConfigurationListener) 

### Actual behavior
At test execution time, I get:
```
   [testng] [TestNG] [ERROR] 
   [testng] Class net.sourceforge.report4s.Listeners does not have a no-args constructor
   [testng] The tests failed.
```

### Is the issue reproducible on runner?

- [X] Shell
- [ ] Maven
- [ ] Gradle
- [X] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
```java
package net.sourceforge.report4s;

import org.testng.*;
import org.testng.xml.*;

class Listeners implements IReporter, ISuiteListener, ITestListener, IConfigurationListener {

	public Listeners() { }

       // Rest of code....
}
```

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="Test web">

	<suite-files>
		<suite-file path="suites/suite-1.xml"/>
		<suite-file path="suites/suite-2.xml"/>
	</suite-files>
	
	<listeners>
                <listener class-name="net.sourceforge.report4s.Listeners" />
        </listeners>
	
</suite>
```
### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by juherr** [comment]
It looks the issue is with a 3rd party listener.

You should report the issue here https://github.com/harmin-parra/report4s

**Comment by harmin-parra** [comment]
That's the code source of the report4s project.

This is a testng issue.

I get compilation errors because my Listener constructor isn't recognized by the Java compiler

**Comment by harmin-parra** [comment]
I cannot reproduce the issue when I implement IConfigurationListener2 instead of IConfiguratioListener.

**Comment by juherr** [comment]
Sorry, I didn't catch the package name of the sample.

**Comment by krmahadevan** [comment]
@harmin-parra - I have tried to reproduce this issue with TestNG `7.8.0` and I am not able to reproduce the problem.

Please help create a sample project which can be used to recreate the issue

**Comment by harmin-parra** [comment]
I don't get the compilation error anymore (maybe due to the presence of 2 different **testng** JAR versions file in classpath ??)

But I get a runtime error

```
test:
   [testng] [main] ERROR org.testng.TestNG - 
   [testng] Cannot instantiate class mypackage.Listeners
```

I created this repo with an example
https://github.com/harmin-parra/testng-bug

**Comment by krmahadevan** [comment]
@harmin-parra - This looks like an issue that is specific to ant. I am not familiar with ant, but I think you could perhaps refer to the sample that I shared https://github.com/testng-team/testng/issues/2910#issuecomment-1556552521 and build upon it. 

Please find attached a sample maven project that demonstrates that the listener is getting called

Output

```shell
[INFO] --- surefire:3.1.0:test (default-test) @ issue-2912 ---
[INFO] Using auto detected provider org.apache.maven.surefire.testng.TestNGProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
beforeConfiguration
onConfigurationSuccess
beforeConfiguration
onConfigurationSuccess
PASSED: com.rationaleemotions.MyTest.myTest2
PASSED: com.rationaleemotions.MyTest.myTest1

===============================================
    My-test
    Tests run: 2, Failures: 0, Skips: 0
===============================================

[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.779 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.181 s
[INFO] Finished at: 2023-05-22T14:44:42+05:30
[INFO] ------------------------------------------------------------------------
```
[issue-2912.zip](https://github.com/testng-team/testng/files/11529336/issue-2912.zip)


Please modify the attached project as needed if the issue you are experiencing continues to exist.
