### ISSUE TITLE
java.lang.NoSuchMethodError: 'void org.testng.TestRunner. appears when running my test on eclipse 

### ISSUE THREAD

**Issue by zanoon2020** [testng-team/testng#2915]
### TestNG Version 7.8.0
> Note: only the latest version is supported

### Expected behavior
test run normally 

### Actual behavior
java.lang.NoSuchMethodError: 'void org.testng.TestRunner.<init>(org.testng.internal.IConfiguration, org.testng.ISuite, org.testng.xml.XmlTest, boolean, java.util.Collection, java.util.List)' 

![image](https://github.com/testng-team/testng/assets/65794900/468142a1-c37d-43c4-b69c-0b1299e40336)

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ yes] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
run any test in maven project

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by juherr** [comment]
It is an eclipse plugin issue.
Please follow https://github.com/testng-team/testng-eclipse/issues/551

**Comment by zanoon2020** [comment]
@juherr thanks very much , will follow mentioned issue

**Comment by adngzz** [comment]
I tracked the issue to https://github.com/testng-team/testng-remote not sure on which side this should be fixed.
https://github.com/testng-team/testng-remote/issues/127

**Comment by zanoon2020** [comment]
solved with latest plugin version
