### ISSUE TITLE
How To Run one @dataprovider against multiple @test methods

### ISSUE THREAD

**Issue by Sayanta-B** [testng-team/testng#2922]
### TestNG Version
TestNg versoin: 7.0.0

### Expected behavior

I want to run multiple @test methods against one @dataprovider 

### Actual behavior

1) I am having multiple @test methods for each test-case but my @dataprovider is executing for first @test method.
### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
DataProvide class-

```java
	public static HashMap<String, String>[][] getDataTable(String fileName, String sheetName) {
		HashMap<String, String>[][] testdata = null;
		HashMap<String, String> tcData = null;
		ArrayList<String> rowHeader = new ArrayList<String>();
		XSSFWorkbook wb = null;
		XSSFSheet ws = null;
		FileInputStream file = null;

		try {
			DataFormatter format = new DataFormatter();
			if (!(fileName.contains("\\") || fileName.contains("/")))
				fileName = "TestData" + File.separator + fileName;

			file = new FileInputStream(fileName);

			wb = new XSSFWorkbook(file);
			if (!sheetName.equals(""))
				ws = wb.getSheet(sheetName);
			else {
				throw new Exception("Don't provide a blank sheet name..");
			}
			int rc = ws.getLastRowNum() + 1;
//			System.out.println("Row count="+ rc);
			int cc = ws.getRow(0).getLastCellNum();
//			System.out.println("Col count="+ cc);
			testdata = new HashMap[rc - 1][1];
			
			XSSFCell headerCell = null;
			XSSFRow row = null;
			XSSFCell cell = null;
			String val = null;
			XSSFRow header = ws.getRow(0);

			for (int k = 0; k < cc; k++) {
				headerCell = header.getCell(k);
				rowHeader.add(headerCell.getStringCellValue()); //rowHeader array list
			}
			for (int i = 1; i < rc; i++) {
				row = ws.getRow(i);
				
				tcData = new HashMap<String, String>();
				for (int j = 0; j < cc; j++) {
					cell = row.getCell(j);
					val = format.formatCellValue(cell);
					tcData.put(rowHeader.get(j), val);
				}
				
				testdata[i - 1][0] = tcData;
			}
		} catch (Exception e) {
			System.out.println("Exception occurred while reading excel sheet." + e.getMessage());
		} finally {
			try {
				if (wb != null)
					wb.close();
			} catch (IOException e) {
				System.out.println("Exception occurred while closing work book." + e.getMessage());
			}
			try {
				if (file != null)
					file.close();
			} catch (IOException e) {
				System.out.println("Exception while closing file input stream." + e.getMessage());
			}
		}
		return testdata;

	}
```	

Test Class:-

```java
 @DataProvider(name = "UserUIOperations")
    public Object[][] createData() {
        try {
            Object[][] retObjArr = DataGenerator.getDataTable(testDataFileName, workSheetName);
            return retObjArr;
        } catch (Throwable e) {
            FrameworkBase.logger.info(e);
            return new Object[][] { {} };
        }
    }
 @Test(dataProvider = "UserUIOperations",dependsOnMethods ="UserCreationWithMandatoryFields" )
    public void case1(HashMap<String, String> input) throws Exception {
    	testCounter=0;
    	UsersUIOperationsTest UIT =new UsersUIOperationsTest();
    	Object[][] testdata=UIT.createData();
    	testCounter++;
  	  for(int i=0;i<testdata.length;i++) { 
  		
		  for(int j=0;j<testdata[i].length;j++) {
	  
	         Map<String,String> element = (Map<String, String>) testdata[i][j]; 
	        
	         String value=element.get("TestDescription");
	        
	         if(value.equals("Delete a user using first name") && testCounter == 1) {
	        	 System.out.println("Executing 3rd  testcase");
	  
    
        FrameworkBase.logger
		.info("================START OF TEST CASE : " + input.get("TestDescription") + "==================");
        String[] test_steps = input.get("TestSteps").split(",");
		for (String test_step : test_steps) {
			FrameworkBase.logger.info("################Executing test step:" + test_step + " ##################");
			switch (test_step) {
			case "Login":
				test_step_status = loginInstance.signIn(input.get(FrameworkConstants.LOGINUSER),
						input.get(FrameworkConstants.LOGINPASSWORD), input.get("TestDescription"));
				break;

			case "CreateUser":
				test_step_status = createUserIntsance.createUser(input.get("FirstName"), input.get("LastName"),
						input.get("CN"), input.get("Password"), input.get("ConfirmPassword"), input.get("Title"),
						input.get("Email"), input.get("Telephone_Number"),

						input.get("Manager"), input.get("DirectReports"), input.get("UserImage"),
						input.get("TestDescription"));

@Test(dataProvider = "UserUIOperations" )
    public void case2(HashMap<String, String> input) throws Exception {
    	testCounter=0;
    	UsersUIOperationsTest UIT =new UsersUIOperationsTest();
    	Object[][] testdata=UIT.createData();
    	testCounter++;
  	  for(int i=0;i<testdata.length;i++) { 
  		
		  for(int j=0;j<testdata[i].length;j++) {
	  
	         Map<String,String> element = (Map<String, String>) testdata[i][j]; 
	        
	         String value=element.get("TestDescription");
	        
	         if(value.equals("Delete a user using first name") && testCounter == 1) {
	        	 System.out.println("Executing 3rd  testcase");
	  
    
        FrameworkBase.logger
		.info("================START OF TEST CASE : " + input.get("TestDescription") + "==================");
        String[] test_steps = input.get("TestSteps").split(",");
		for (String test_step : test_steps) {
			FrameworkBase.logger.info("################Executing test step:" + test_step + " ##################");
			switch (test_step) {
			case "Login":
				test_step_status = loginInstance.signIn(input.get(FrameworkConstants.LOGINUSER),
						input.get(FrameworkConstants.LOGINPASSWORD), input.get("TestDescription"));
				break;

			case "CreateUser":
				test_step_status = createUserIntsance.createUser(input.get("FirstName"), input.get("LastName"),
						input.get("CN"), input.get("Password"), input.get("ConfirmPassword"), input.get("Title"),
						input.get("Email"), input.get("Telephone_Number"),

						input.get("Manager"), input.get("DirectReports"), input.get("UserImage"),
						input.get("TestDescription"));
```

In this case, First @Test is executing but 2nd @Test is not.

Kindly help me on above issue..

**Comment by krmahadevan** [comment]
Please use the [Google groups](https://groups.google.com/g/testng-users) for getting help on TestNG. We would like to restrict the github issues page to bugs/feature requests only.


In your case, you should be using a factory powered data provider (See example below)

```java
import static org.assertj.core.api.Assertions.assertThat;

import java.util.Map;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

public class ExampleTestCase {

  private final Map<String, String> data;

  @Factory(dataProvider = "dp")
  public ExampleTestCase(Map<String, String> input) {
    this.data = input;
  }

  @DataProvider(name = "dp")
  public static Object[] getTestData() {
    return new Object[]{
        Map.of("name", "Dragon-Warrior"),
        Map.of("name1", "Po") // This will cause failures for 2nd iteration
    };
  }

  @Test
  public void firstTest() {
    assertThat(this.data).containsKey("name");
  }

  @Test(dependsOnMethods = "firstTest")
  public void secondTest() {
    assertThat(this.data.get("name")).isNotNull();
  }
}

```

**Comment by Sayanta-B** [comment]
[Google groups](https://groups.google.com/g/testng-users) not responded .
After implementing the @Factory methods getting error
@Factory(dataProvider="UserUIOperations")
    public UsersUIOperationsTest(HashMap<String, String> input) {
    	
    	data=new  HashMap<String, String>();
    	this.data=input;
    	
    }
   

    @DataProvider(name = "UserUIOperations")
    public Object[][] createData() {
        try {
            Object[][] retObjArr = DataGenerator.getDataTable(testDataFileName, workSheetName);
            return retObjArr;
        } catch (Throwable e) {
            FrameworkBase.logger.info(e);
            return new Object[][] { {} };
        }
    }

Error:-
org.testng.TestNGException: 
Cannot instantiate class com.microfocus.idmappsui.tests.UsersUIOperationsTest
	at org.testng.internal.InstanceCreator.newInstance(InstanceCreator.java:36)
	at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:40)
	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:30)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:651)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:553)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
	at org.testng.internal.FactoryMethod.invoke(FactoryMethod.java:149)
	at org.testng.internal.TestNGClassFinder.processFactory(TestNGClassFinder.java:182)
	at org.testng.internal.TestNGClassFinder.processMethod(TestNGClassFinder.java:142)
	at org.testng.internal.TestNGClassFinder.processClass(TestNGClassFinder.java:133)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:71)
	at org.testng.TestRunner.initMethods(TestRunner.java:443)
	at org.testng.TestRunner.init(TestRunner.java:339)
	at org.testng.TestRunner.init(TestRunner.java:292)
	at org.testng.TestRunner.<init>(TestRunner.java:223)
	at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
	at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
	at org.testng.ITestRunnerFactory.newTestRunner(ITestRunnerFactory.java:55)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:659)
	at org.testng.SuiteRunner.init(SuiteRunner.java:173)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:107)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1300)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1276)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.InstantiationException: com.microfocus.idmappsui.tests.UsersUIOperationsTest
	at java.base/java.lang.Class.newInstance(Class.java:571)
	at org.testng.internal.InstanceCreator.newInstance(InstanceCreator.java:30)
	... 28 more
Caused by: java.lang.NoSuchMethodException: com.microfocus.idmappsui.tests.UsersUIOperationsTest.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	... 29 more
Please help me with this.
