### ISSUE TITLE
Add support for temporary directory creation with annotations

### ISSUE THREAD

**Issue by vlsi** [testng-team/testng#2926]
### TestNG Version

latest

### Expected behavior

There should be a way to create and use temporary directory for the test.

### Actual behavior

Users have to manage directories on their own :-/

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

See https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory

Frankly speaking, I am not sure if it makes sense to duplicate "extensions" approach in TestNG, however, it would be nice if there was a possibility to create temp dirs in TestNG-based tests.

**Comment by juherr** [comment]
I'm not sure it should be done in the core but it could be done into 3rd party extension like https://github.com/sbabcoc/TestNG-Foundation

Something like the `SharedTempDirectoryDemo` (from JUnit's documentation) should be easy to do with listeners.

**Comment by vlsi** [comment]
I have not seen TestNG-Foundation before.
I just tried to use `@TempDir` in TestNG-based project and realized it does not work like that :-)

For now, I went with jimfs, and it works, so I close the ticket for now.
