### ISSUE TITLE
afterMethod of superclass is running when “exclude” tag present in the testng suite & alwaysRun=true is not set

### ISSUE THREAD

**Issue by ashwini-123** [testng-team/testng#2931]
_### TestNG Version
org.testng_7.4.0.r202105021533.jar
> Note: only the latest version is supported

### Expected behavior
afterMethod of superclass should not be running when “exclude” tag present in the testng suite & alwaysRun=true is not set

### Actual behavior
afterMethod of superclass is running when “exclude” tag present in the testng suite & alwaysRun=true is not set

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

##Superclas

```java
public class ClassTest {
	@BeforeMethod
	public void beforeMethod(){
		System.out.println("In beforeMethod of ClassTest");
	}
	@Test(groups = { "liux.jboss.oracle", "acceptance" })
	public void testOnLinuxJbossOracleStack() {
		System.out.println("In testOnLinuxJbossOracleStack of ClassTest");
	}
	@Test(groups = {"aix.was.db2", "regression"} )
	public void testOnAixWasDb2Stack() {
		System.out.println("In testOnAixWasDb2Stack of ClassTest");
	}
	@Test(groups = "acceptance")
	public void testAcceptance() {
		System.out.println("In testAcceptance of ClassTest");
	}
	@Test(groups = "regression")
	public void testRegression(){
		System.out.println("In testRegression of ClassTest");
	}
	@AfterMethod
	public void afterMthod(){
		System.out.println("In afterMthod of ClassTest");
	}
	@BeforeSuite
	public void beforeSuite() {
		System.out.println("In beforeSuite of ClassTest");
		//System.out.println();
	}
	@AfterSuite
	public void afterSuite() {
		System.out.println("In afterSuite of ClassTest");
		System.out.println();
	}
}
```

##subclass

```java
public class NewTest2 extends ClassTest{
  @Test(groups = {"functest","checkinterest"})
  public void newTestMethod1() {
	  System.out.println("In newTestMethod1 of NewTest2");
  }  
  @Test(groups = {"functest"})
  public void newTestMethod2() {
	  System.out.println("In newTestMethod2 of NewTest2");
  }  
  @Test(groups = {"checkinterest"})
  public void newTestMethod3() {
	  System.out.println("In newTestMethod3 of NewTest2");
  }
  @BeforeMethod
  public void beforeMethod() {
	  System.out.println("In beforeMethod of NewTest2");
  }
  @AfterMethod
  public void afterMethod() {
	  System.out.println("In afterMethod of NewTest2");
	  System.out.println();
  }
  @BeforeClass
  public void beforeClass() {
	  System.out.println("In beforeClass of NewTest2");
  }
  @AfterClass
  public void afterClass() {
	  System.out.println("In afterClass of NewTest2");
	  System.out.println();
  }
  @BeforeTest
  public void beforeTest() {
	  System.out.println("In beforeTest of NewTest2");
	  //System.out.println();
  }
  @AfterTest
  public void afterTest() {
	  System.out.println("In afterTest of NewTest2");
	  System.out.println();
  }
  @BeforeSuite
  public void beforeSuite() {
	  System.out.println("In beforeSuite of NewTest2");
	  //System.out.println();
  }
  @AfterSuite(alwaysRun = true)
  public void afterSuite() {
	  System.out.println("In afterSuite of NewTest2");
	  System.out.println();
  }
}
```

##testng.xml

```xml
<suite name="Grouptest" verbose="1" >
  <test name="Group" >
  <groups>
 <run>
  <!-- <include name="checkinterest"/> -->
  <exclude name="functest"/>
  </run>
  </groups>
    <classes>
       <class name="com.ashwini.lanjey.NewTest2" />
    </classes>
  </test>  
</suite>
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps._

**Comment by juherr** [comment]
Hi,

I don't understand why you think there is an issue.
The afterMethod is part of the suite because it has no group.

Could you precise your mind?

**Comment by ashwini-123** [comment]
Hi,

If  "afterMethod" is part of the suite then "beforeMethod" is also part of
the suite. Why is that not called?
And why afterMethod is called when "exclude" tag is used and it is not
called when "include" tag is used?

Thanks & Rregards
Ashwini Lanjey

**Comment by krmahadevan** [comment]
@ashwini-123 - When you say exclude `functest` group, what you are essentially telling TestNG is that, execute everything else, except those methods that belong to `functest` group.

So in this case, the afterMethod is getting executed, because it is not belonging to any group and so, it essentially means it becomes eligible for being executed.

Does that answer your question ? This is essentially what @juherr was trying to explain as well.

**Comment by shubhamind08** [comment]
We can try replacing always run with enabled to remove the dependence of the current modules on others.

**Comment by krmahadevan** [comment]
No response from user. Closing this ticket.
