### ISSUE TITLE
Regression: @Ignore on method level doesn't work as expected

### ISSUE THREAD

**Issue by youming-lin** [testng-team/testng#2977]
Latest TestNG version(s) has regressed from a fix put into 7.4.0 here: https://github.com/testng-team/testng/issues/2396

### TestNG Version
> Note: only the latest version is supported

Tested on 7.5, 7.8.0

### Expected behavior
Test methods annotated with `@Ignore` should be ignored by the test runner.

Per Javadoc, `@Ignore` is, and I quote, **`Alternative of @Test(enabled=false)`**. Yet this is not the case. See example code below.

### Actual behavior
Test methods annotated with `@Ignore` are still executed by the test runner.

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Sample code:
```
package example.test;

import static org.testng.Assert.fail;

import org.testng.annotations.Ignore;
import org.testng.annotations.Test;

public class TestNGEclipseIgnoreBug {
    @Test(enabled = false)
    public void testEnabledFalse() {
        fail("Test is not enabled");
    }

    @Test
    @Ignore
    public void testIgnored() {
        fail("Test is ignored");
    }
}
```

If using TestNG 7.4.0, executing test on the class results in:
```
[RemoteTestNG] detected TestNG version 7.4.0

===============================================
    Default test
    Tests run: 0, Failures: 0, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 0, Passes: 0, Failures: 0, Skips: 0
===============================================

[TestNG] No tests found. Nothing was run

<rest omitted>
```
Test is ignored expected with the fix in 7.4.0. as reported in the original issue.

If using TestNG 7.5 or 7.8.0 (latest version as of time of post), executing test on the class results in:
```
[RemoteTestNG] detected TestNG version 7.8.0
log4j:WARN No appenders could be found for logger (org.testng.TestNG).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
FAILED: example.test.TestNGEclipseIgnoreBug.testIgnored
java.lang.AssertionError: Test is ignored

<rest omitted>
```
`@Ignore`'d test method is still executed and results in test failure.

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
@youming-lin - This seems to be a problem specific to TestNG eclipse plugin perhaps? 

Can you please run the below sample and tell me what you see? I dont see issue that you are experiencing.

```java
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestResult;
import org.testng.TestNG;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class IssueMain {

  public static void main(String[] args) {
    TestNG testng = new TestNG(false);
    testng.setTestClasses(new Class[]{TestNGEclipseIgnoreBugSample.class});
    InvokedMethodListener listener = new InvokedMethodListener();
    testng.addListener(listener);
    testng.run();
    assertThat(listener.invokedMethods).isEmpty();
  }

  public static class InvokedMethodListener implements IInvokedMethodListener {
    final List<String> invokedMethods = new ArrayList<>();

    @Override
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
      invokedMethods.add(method.getTestMethod().getMethodName());
    }
  }
}
```

If the problem still exists when running via eclipse, then you should perhaps file this issue on https://github.com/testng-team/testng-eclipse

@missedone - FYI

**Comment by youming-lin** [comment]
@krmahadevan Thanks for checking!
I created a new project with just this test class and cannot reproduce this any more (neither running `mvn test` nor through TestNG Eclipse plugin). Not sure what is going with the original project's configuration.

**Comment by ramtech123** [comment]
I have same issue with @Ignore annotation, individual tests are disabled only when using `enabled = false`.

- Gradle 7.6,
- Verified with different versions of testng 
-- 7.5.1 and 7.8.0 - `@Ignore` annotation at method level is not working in both cases
-- 7.4.0 - `@Ignore` annotation disables the test, as expected.

(PS: not using eclipse)

Was there any issue / resolution that was identified? Thanks

**Comment by krmahadevan** [comment]
@ramtech123 - Please share a sample project that can be used to reproduce the problem
