### ISSUE TITLE
Data Provider Threads configuration in the suite don't match the documentation

### ISSUE THREAD

**Issue by bennid** [testng-team/testng#2980]
### TestNG Version
7.8.0

### Expected behavior

Data providers can run in parallel with the attribute parallel:
@DataProvider(parallel = true)
// ...
Parallel data providers running from an XML file share the same pool of threads, which has a size of 10 by default. You can modify this value in the <suite> tag of your XML file:
<suite name="Suite1" data-provider-thread-count="20" >
...

### Actual behavior
TestNG seems to startup "tests" that startup the dataprovider threads, and the data provider thread count is spun up per test.  So if there are 4 data-provider tests each with 10 instances, if you set the data-provider-thread-count to 10, instead of only 10 data-provider tests running in parallel, the 4 "original tests" will spin up 10 data-providers each.  Setting the thread-count is how many "tests" startup the data-provider threads.

https://github.com/bennid/testng-data-provider-threads

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
https://github.com/bennid/testng-data-provider-threads

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by bennid** [comment]
After a bit of searching, it seems like this is similar / the same as https://github.com/testng-team/testng/issues/2019

**Comment by bennid** [comment]
The reason we need this solved, is that we only have a certain number of licenses for our remote selenium service.  In this suite we have ~12 tests that each have 7 data provider instances in addition to another 12 basic tests.  We can only run ~30 tests at a time in parallel to not utilize all our licenses.  In working on the suite file, I've setup the DP tests to run first w/ 8 threads, and 4 dp-threads (So a max of 32).  Then run the basic tests after.  However, this is still wasting time (we want to get the 90 some-odd tests running at around 25-30 at a time to speed up the result.

[consurrency-graph](https://github.com/bennid/testng-data-provider-threads/blob/main/src/test/resources/Screenshot%202023-09-15%20at%204.00.55%20PM.png)

**Comment by krmahadevan** [comment]
> After a bit of searching, it seems like this is similar / the same as #2019

No. This issue is not similar to #2019. I believe that issue talks about having a global thread pool which is going to be shared by data driven tests and non data driven tests.

This issue you raised is specific to just having the data driven tests honour the thread pool value set globally. 
To fix this, I have raised a PR which essentially adds a new attribute to the TestNG DTD so that you can now explicitly configure TestNG to use a shared thread pool for all your data providers or you can have it setup via a configuration, which will automatically enforce this in all the suites being run.
