### ISSUE TITLE
Downloading external sources is disabled TestNG.xml

### ISSUE THREAD

**Issue by RYenike** [testng-team/testng#2994]
### TestNG Version : 7.4.0
> Note: only the latest version is supported

### Expected behavior
Downloading external sources is disabled TestNG.xml error should not displayed

### Actual behavior
Downloading external sources is disabled TestNG.xml error is displayed

### Is the issue reproducible on runner?
Operating System - Ubuntu
- [ ] Shell
- [ ] Maven -- 3.9.5
![Screenshot from 2023-10-08 13-50-58](https://github.com/testng-team/testng/assets/140067876/b52fc15a-9f97-4b9e-a34e-b318b273f3b1)

- [ ] Gradle
- [ ] Ant
- [ ] Eclipse - Version: 2023-09 (4.29.0)
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
This is NOT a TestNG problem. It looks like a problem related to your machine and eclipse NOT being able to download the XSD. 

You would need to check this checkbox (Download external resources like referenced DTD, XSD) in preferences/settings

<img width="715" alt="image" src="https://github.com/testng-team/testng/assets/909773/e2cec842-b073-49b8-b636-809242ffbab5">
