### ISSUE TITLE
Cascading suite xml's are not run from jar with -xmlpathinjar, only initial xml

### ISSUE THREAD

**Issue by ZathrasOne** [testng-team/testng#2995]
### TestNG Version
> 7.8.0

### Expected behavior
(Sorry about the resubmission, I got busy at work with other items)
When running XML from a jar, and that XML includes a suite-file, TestNG should look in the jar for that file as well

### Actual behavior
TestNG looks on disk instead of in the jar
Example command>java -cp ./* org.testng.TestNG -testjar TestngEmbeddedSuitesTest-0.0.1-SNAPSHOT-jar-with-dependencies.jar -xmlpathinjar src/TestNG/masterSuite.xml
[TestNG] [ERROR] java.io.FileNotFoundException: C:\Users\brucer\SuiteTEST\src\TestNG\suite1.xml (The system cannot find the path specified)

### Is the issue reproducible on runner?

- [X] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Project attached (note: although this is an Eclipse project, I am building the jar file with Maven from the command line in-place)
To execute after running an mvn package
TestngEmbeddedSuitesTest>CD target
TestngEmbeddedSuitesTest\target>Exec_Test

Remember, this must be run in a directory that does NOT have the secondary xml files in the expected location (src/TestNG/), otherwise TestNG will just use those. That is why I have put a copy of the .bat file that contains the exact command to run in the target directory. If you run in your dev environment in place (you can use that method to check what the operation SHOULD look like), it will just use the xml on disk and not complain, but also not test the correct configuration.

### Contribution guidelines

[TestngEmbeddedSuitesTest.zip](https://github.com/testng-team/testng/files/12850934/TestngEmbeddedSuitesTest.zip)

**Comment by krmahadevan** [comment]
I revisited this using the sample project and after making the below changes to the sample project, it works

```xml
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="Main suite"> <!--commenting parallel="suite-file" thread-count="2" -->
    <test name="Test Patients tests">
        <classes>
            <class name="org.testng.test.class1" >
                <methods>
                    <include name="method1" />
                </methods>
            </class>
        </classes>
    </test>
    <!-- Notice that you should specify the path of the child suite files with respect to the 
    parent suite file -->
	<suite-files>
		<suite-file path="Suite1.xml" />
		<suite-file path="Suite2.xml" />
	</suite-files>
</suite>
```

Modified the assembly plugin to be something like this:

```xml
<plugin>
    <artifactId>maven-assembly-plugin</artifactId>
    <configuration>
        <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
        <!-- Enhanced the plugin to ensure that the archive includes reference to
        TestNG main class -->
        <archive>
            <manifest>
                <mainClass>org.testng.TestNG</mainClass>
            </manifest>
        </archive>
    </configuration>
    <executions>
        <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
                <goal>single</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
Created a shell script (since am NOT on windows) that looks like below:

```shell
java -jar target/TestngEmbeddedSuitesTest-0.0.1-SNAPSHOT-jar-with-dependencies.jar -testjar  -xmlpathinjar src/TestNG/masterSuite.xml
```

Here's the execution output

```shell
➜  TestngEmbeddedSuitesTest ./run.sh
295 [main] INFO org.testng.internal.Utils - [TestNG] Running:
  /Users/kmahadevan/githome/playground/github_issues/TestngEmbeddedSuitesTest/src/TestNG/Suite1.xml

Executing class 1 method1

===============================================
Service Operations tests
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================

537 [main] INFO org.testng.internal.Utils - [TestNG] Running:
  /Users/kmahadevan/githome/playground/github_issues/TestngEmbeddedSuitesTest/src/TestNG/Suite2.xml

Executing class 2 method1

===============================================
Service Operations tests (0)
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================

540 [main] INFO org.testng.internal.Utils - [TestNG] Running:
  /Users/kmahadevan/githome/playground/github_issues/TestngEmbeddedSuitesTest/src/TestNG/masterSuite.xml

Executing class 1 method1

===============================================
Main suite
Total tests run: 3, Passes: 3, Failures: 0, Skips: 0
===============================================
```

Closing this issue
