### ISSUE TITLE
How to achieve test to be executed in particular order

### ISSUE THREAD

**Issue by suryanshagnihotri** [testng-team/testng#3018]
### TestNG Version
> Note: only the latest version is supported
7.8.0

### Expected behavior
I am using below xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Parent_Suite">
    <test name="group test " preserve-order="true">
        <classes>
            <class name="NewTest">
                <methods>
                    <include name="testCase3" />
                </methods>
            </class>
            <class name="NewTest2">
                <methods>
                    <include name="testCase2" />
                </methods>
            </class>
            <class name="NewTest">
                <methods>
                    <include name="testCase1" />
                </methods>
            </class>
        </classes>
    </test>
</suite>
```

I want test to be be executed in NewTest:testCase3 then NewTest2:testCase2 and at last NewTest:testCase1.
But it is not following it.

### Actual behavior
It is executing all tests of NewTest and then NewTest2.

in test case 1 of NewTest
in test case 3 of NewTest
in test case 2 of NewTest2

### Is the issue reproducible on runner?
Easily reproducible.

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
```
import org.testng.annotations.Test;
public class NewTest {
    @Test()
    public void testCase1() {
        System.out.println("in test case 1 of NewTest");
    }
    @Test()
    public void testCase2() {
        System.out.println("in test case 2 of NewTest");
        assert false;
    }
    @Test()
    public void testCase3() {
        System.out.println("in test case 3 of NewTest");

    }
}
```

```
import org.testng.annotations.Test;
public class NewTest2 {
    @Test()
    public void testCase1() {
        System.out.println("in test case 1 of NewTest2");
    }
    @Test()
    public void testCase2() {
        System.out.println("in test case 2 of NewTest2");
        assert true;
    }
    @Test()
    public void testCase3() {
        System.out.println("in test case 3 of NewTest2");
    }
}
```

Is it possible to achieve or not?

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
@suryanshagnihotri - AFAIK, this is NOT possible. From looking at the codebase, TestNG is grouping methods that belong to the same class together and then running them honouring the order in which they occur in the suite file.

For your usecase, you might want to split the 3rd method into a different `<test>` tag.
