### ISSUE TITLE
Remove deprecated JUnit related support in TestNG

### ISSUE THREAD

**Issue by krmahadevan** [testng-team/testng#3022]
### TestNG Version
> Note: only the latest version is supported

`7.9.0`

### Expected behavior

TestNG need not support JUnit anymore now.

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

JUnit3/JUnit4 support in TestNG was deprecated as of `v7.7.0`.  This was done because the JUnit team have enhanced JUnit5 to support running TestNG using JUnit itself. So there's no need for TestNG to do the reverse of this and TestNG users can switch over to using JUnit5 if they have a mixture of JUnit and TestNG tests and need both of them to be executed by the same test runner (JUnit5 would be the driver which would internally invoke TestNG)

For more details please refer to the official documentation of the testng-engine by JUnit at https://github.com/junit-team/testng-engine

**Comment by bobshie** [comment]
That's to say, the Junit4 Testcase will not running with TestNG 7.10.0~.  should Junit5 work well with TestNG latest version.

**Comment by juherr** [comment]
@bobshie Yes. With https://github.com/junit-team/testng-engine JUnit5 should be able to run JUnit4, JUnit5 et TestNG test cases together. Please share your experience on testng-engine if something is not working as expected.

**Comment by bobshie** [comment]
Hello, We have Junit4 test cases that based on Junit4, but after we uplift testng to 7.10.2, these test cases isnot running. 

I changed the dependent from 
`<dependency>
             <groupId>junit</groupId>
             <artifactId>junit</artifactId>
             <version>${junit.version}</version>
             <scope>${junit.scope}</scope>
         </dependency>
`

to 
`
<dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>5.10.2</version>
            <scope>${junit.scope}</scope>
        </dependency>
`
then it works. 
the whole dependency list is: 
`
        <dependency>
             <groupId>org.testng</groupId>
             <artifactId>testng</artifactId>
            <version>7.10.2</version>
         </dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>5.10.2</version>
            <scope>${junit.scope}</scope>
        </dependency>
        
     </dependencies>
`
