### ISSUE TITLE
Unable to inject ITestContext in @BeforeSuite

### ISSUE THREAD

**Issue by natalywadie** [testng-team/testng#3029]
### TestNG Version
7.9.0

### Expected behavior
To be able to inject ITestContext in `@BeforeSuite`. A use case is to retrieve the suite name and details to initialize a report with the run details.

### Actual behavior
An error started occurring in the new version while injecting the ITestContext parameter indicating that injection is not supported.

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

#### Sample Test Class
```java
import org.testng.ITestContext;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

public class SampleTest {

    @BeforeSuite
    public void beforeSuite(ITestContext context) {
        System.out.println("Suite name: " + context.getName());
    }

    @Test
    public void test1() {
        System.out.println("Test 1 running");
    }
}
``` 

#### Sample Suite
```
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Sample Test" configfailurepolicy="continue">
    <test name="Sample">
        <classes>
            <class name="SampleTest"/>
        </classes>
    </test>
</suite>
```

#### Expected Output
```
Suite name: Sample
Test 1 running
```

#### Actual Output
```
org.testng.TestNGException: 
Native Injection is NOT supported for @BeforeSuite annotated beforeSuite.
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection

	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:445)
	at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:350)
	at org.testng.internal.Parameters.createParameters(Parameters.java:702)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:166)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:306)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)


Test ignored.

===============================================
Sample Test
Total tests run: 1, Passes: 0, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 0
===============================================
```

**Comment by krmahadevan** [comment]
@natalywadie - Thanks for logging this issue. TestNG is working as designed in this case [ But the documentation is NOT upto date and needs to be fixed. I will fix it ]

At a suite level, there's no information available pertaining to a `<test>` tag. `ITestContext` is the object representation of `<test>` tag. So it doesn't make sense to access it from a suite level.

You could do a `Reporter.getCurrentTestResult()` and see if that lets you access what you need. Else you would have to do this via a TestNG listener only.

**Comment by natalywadie** [comment]
@krmahadevan But there are more info in the suite other than test results that can still be accessed/needed in BeforeSuite functions, why block the whole access instead of only disabling access to results?

**Comment by krmahadevan** [comment]
@natalywadie - Can you please help elaborate your exact usecase for which you are looking to solve via a `@BeforeSuite` annotation? When one is at a Suite level parsing, `<test>` tag level parsed information is NOT relevant, because it's still not processed. And if it is processed which `<test>` information should be injected because a `<suite>` can have multiple `<test>` tags available in it.

**Comment by natalywadie** [comment]
@krmahadevan - Sure, my use case is needing the suite name (not any `<test>` tag) and/or `ITestContext.getName()` to be used in initializing the external report's title and file name.
I agree that `<test>` tag level is not relevant at this point, but other properties still exist within `<suite>` tag that can be useful before any tests start running.

**Comment by krmahadevan** [comment]
@natalywadie - You should be able to do something like this

```java
import org.testng.ISuite;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

public class DemoClass {

    @BeforeSuite
    public void beforeSuite() {
        ITestResult itr = Reporter.getCurrentTestResult();
        ISuite suite = itr.getTestContext().getSuite();
        System.err.println("Suite name " + suite.getName());
    }

    @Test
    public void testMethod() {

    }
}
```

**Comment by natalywadie** [comment]
@krmahadevan - Thank you, working as expected.
