### ISSUE TITLE
There was an error in the forked process after upgrade testng

### ISSUE THREAD

**Issue by bakicanboydas** [testng-team/testng#3030]
### TestNG Version
7.9.0

### Expected behavior
With version 7.8.0 this error does not occur

### Actual behavior

```
# Created at 2024-01-02T10:42:13.568
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at org.testng.internal.Attributes.setAttribute(Attributes.java:25)
	at org.testng.TestRunner.setAttribute(TestRunner.java:1297)
	at utils.listeners.TestListener.onStart(TestListener.java:38)
	at org.testng.TestRunner.fireEvent(TestRunner.java:949)
	at org.testng.TestRunner.beforeRun(TestRunner.java:646)
	at org.testng.TestRunner.run(TestRunner.java:612)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

I switched from version 7.8.0 to version 7.9.0 without making any changes and I started to get this error.

**Comment by krmahadevan** [comment]
@bakicanboydas - Please add a sample project that can be used to reproduce this problem.

**Comment by bakicanboydas** [comment]
@krmahadevan  I cannot share it because it is a company project, but I can share pom versions. I changed where our company name used in pom file other things that i can publish with you. I can't publish project because of NDA sorry.

<?xml version="1.0" encoding="UTF-8" standalone="no"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>OUR COMPANY NAME</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <surefire.plugin.version>3.0.0-M5</surefire.plugin.version>
    </properties>


    <dependencies>

        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>7.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.4.0</version>
            
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>5.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.14.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.14.1</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.26</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>2.25.0</version>
        </dependency>
        <dependency>
            <groupId>OUR COMPANY NAME</groupId>
            <artifactId>COMPANY ARTIFACT ID</artifactId>
            <version>1.0.main.80</version>
        </dependency>
        <dependency>
            <groupId>com.browserstack</groupId>
            <artifactId>browserstack-java-sdk</artifactId>
            <version>LATEST</version>
            <scope>compile</scope>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.10</version>
        </dependency>

    </dependencies>

    <build>
        <pluginManagement>
            <plugins>



                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.1</version>
                    <configuration>
                        <source>11</source> 
                        <target>11</target> 
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M5</version>
                    <configuration>
                        <testFailureIgnore>true</testFailureIgnore>
                        <shutdown>kill</shutdown>
                        <suiteXmlFiles>
                            <suiteXmlFile>testngSuites/testng.xml</suiteXmlFile>
                        </suiteXmlFiles>

                        <argLine>
                            -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/1.9.6/aspectjweaver-1.9.6.jar"
                        </argLine>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.aspectj</groupId>
                            <artifactId>aspectjweaver</artifactId>
                            <version>1.9.6</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <plugin>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>3.6.1</version>
                    <executions>
                        <execution>
                            <id>getClasspathFilenames</id>
                            <goals>
                                <goal>properties</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.6.1</version>
        <executions>
          <execution>
            <id>getClasspathFilenames</id>
            <goals>
              <goal>properties</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>OUR COMPANY NAME</id>
            <url>OUR COMPANY ARTIFACT URL</url>
        </repository>

    </distributionManagement>
    <repositories>
        <repository>
            <id>OUR COMPANY NAME</id>
            <url>OUR COMPANY ARTIFACT URL</url>
            <releases>
            </releases>
            <snapshots>
            </snapshots>
        </repository>
    </repositories>

</project>

**Comment by krmahadevan** [comment]
@bakicanboydas - I am not asking you to share your company project, but merely asking you to please help share a sample project which I can use to reproduce the problem. Without a sample its not going to be possible to figure out what is going on. 

So please help with a sample project.

**Comment by krmahadevan** [comment]
Also if you look at the stacktrace you would notice that its one of your test listeners which seem to be the source of the NullPointerException

```
at utils.listeners.TestListener.onStart(TestListener.java:38)
```

Perhaps you could help setup a breakpoint there and see what is being passed as the key/value to the `ITestResult` object's attributes. That should tell you what is going wrong.

**Comment by bakicanboydas** [comment]
@krmahadevan  These are steps with debug for 7.9.0 result
<img width="679" alt="Screenshot 2024-01-02 at 14 51 36" src="https://github.com/testng-team/testng/assets/23619308/8c516028-cc22-4e98-b94e-2f2cb0deb0c5">
<img width="1022" alt="Screenshot 2024-01-02 at 14 50 29" src="https://github.com/testng-team/testng/assets/23619308/6aacfb36-2291-4dfb-b75a-034555e37c6c">
<img width="738" alt="Screenshot 2024-01-02 at 14 51 00" src="https://github.com/testng-team/testng/assets/23619308/0f000b27-50dc-4b9a-92b2-c95292ad6773">

**Comment by krmahadevan** [comment]
@bakicanboydas 

> These are steps with debug for 7.9.0 result, what is different between 7.9.0 and 7.8.0 for this part?

It looks like your `driver` object is `null`.  Please check/share how the `this.driver` is being instantiated to find out why it's coming up as null.

**Comment by bakicanboydas** [comment]
I instantiated it in BaseTest and extend it on Listener class

**Comment by bakicanboydas** [comment]
I instantiated it in BaseTest and extend it on Listener class
<img width="321" alt="Screenshot 2024-01-02 at 15 10 17" src="https://github.com/testng-team/testng/assets/23619308/64936738-f7cb-4b9c-af06-94fa59777ed3">
<img width="593" alt="Screenshot 2024-01-02 at 15 10 29" src="https://github.com/testng-team/testng/assets/23619308/f583200d-06f2-43ac-9e6f-476c899e7a97">

**Comment by krmahadevan** [comment]
Please show the place wherein Appium is being instantiated. Your screenshot just shows where AppiumDriver is declared. 

Instead of this back and forth is why I was suggesting that you please create a sample that can be used to reproduce the problem.

**Comment by krmahadevan** [comment]
No response from user. Closing this ticket.
