### ISSUE TITLE
Drop ant support

### ISSUE THREAD

**Issue by juherr** [testng-team/testng#3033]
And maybe propose to contribute the classes under the ant project.
https://lists.apache.org/list.html?dev@ant.apache.org

**Comment by juherr** [comment]
Hi @recursive-rat4 We are going to move ant under a dedicated repository. Could you explain your vote?

**Comment by recursive-rat4** [comment]
I'm looking to switch from Gradle to Maven or Ant and stumbled upon this issue. Perhaps your intention was misread, the move to separate repository sounds OK.

**Comment by krmahadevan** [comment]
> I'm looking to switch from Gradle to Maven or Ant and stumbled upon this issue. Perhaps your intention was misread, the move to separate repository sounds OK.

@recursive-rat4 - Just curious. What would be the reason behind you wanting to opt out of Gradle. I have seen people move out from maven into gradle. Just wanted to know.

**Comment by recursive-rat4** [comment]
@krmahadevan Some years ago, I saw a need to redesign a C++ project and chose Kotlin (coroutines, serialization, portability, all the cool stuff...). Indeed, seeing people move to Gradle was the factor to select this build tool. It never satisified me personally. What's really importrant, free software distributions face issues like https://github.com/gradle/gradle/issues/26516
