### ISSUE TITLE
TestNG @Transform method is not been called when running from IntelliJ IDE Level

### ISSUE THREAD

**Issue by kherath17** [testng-team/testng#3043]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
@Transform annotation should be executed when running from IDE level as well

### Actual behavior

```java
@Override
public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
        annotation.setRetryAnalyzer(RetryAnalyzer.class);
}
```

Above method is defined with its respective retrying logic in a custom listener class which implements `ITestListener` and `IAnnotationTransformer` interfaces , but when test is executed from IntelliJ IDE level and when runs into assertion failure the retry logic is not executed due to `@Transform` method not been called

_**But when a .xml file is executed defining the listener and test class through a mvn command it works successfully.**_

### Is the issue reproducible on runner?

- [ ] Shell
- [] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```java
@Listener(MyCustomListener.class)
public class test1 {
    @Test
    public void nav(){
        WebDriverManager.chromeDriver.setup();
         driver.get("https://www.google.com/");
        Assert.assertEquals(driver.getTitle(),"TTT");
    }
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
TestNG is working as designed.

Details are available in the javadocs of [`@Listeners`](https://javadoc.io/doc/org.testng/testng/latest/org/testng/annotations/Listeners.html) annotation.

`IAnnotationTransformer` should not be wired in via the `@Listeners` annotation. It should be injected in via the `<listeners>` tag (or) using service loading.

More information about listeners can be found [here](https://testng.org/#_testng_listeners)

**Comment by krmahadevan** [comment]
Please check this documentation as well (I have enhanced it just now) https://testng.org/annotation_transformers.html

**Comment by kherath17** [comment]
@krmahadevan  Thank You , appreciate your prompt response
