### ISSUE TITLE
Listener's "before" and "after" methods should be executed in the same thread as the test itself

### ISSUE THREAD

**Issue by asolntsev** [testng-team/testng#3044]
### TestNG Version
7.9.0

### Expected behavior
I have a listener with methods `beforeInvocation` and `afterInvocation` (or, say, `onTestStart`/`onTestSuccess`/`onTestFailure`).
They prepare some `ThreadLocal` objects (used during the test or after the test).

I expect TestNG to execute them **in the same thread** as the test itself.

### Actual behavior
TestNG runs all Listeners' methods in `main` thread, but my test - in different thread (`TestNG-method=mySuperTest-1`).
`ThreadLocal`s stay untouched.

### Is the issue reproducible on runner?

- [x] Shell
- [x] Maven
- [x] Gradle
- [x] Ant
- [x] Eclipse
- [x] IntelliJ
- [x] NetBeans

### Test case sample
A sample project that reproduces the problem:
https://github.com/asolntsev/testng-threads-sample/

**Comment by krmahadevan** [comment]
This is related to https://github.com/testng-team/testng/issues/914

**Comment by krmahadevan** [comment]
@asolntsev - Can you please track this via #914 ?

In the meantime please check if using `InheritableThreadLocal` helps you get past the problem.

Here's a sample

```java
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestResult;

import java.util.UUID;

public class SampleListener implements IInvokedMethodListener {

    public static final ThreadLocal<String> tracker = new InheritableThreadLocal<>() {
        @Override
        protected String initialValue() {
            String text = UUID.randomUUID().toString();
            System.err.println("Setting the initial value :" + text);
            return text;
        }
    };

    @Override
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
        String testMethod = testResult.getMethod().getMethodName();
        System.err.println("[beforeInvocation()] Thread id " + Thread.currentThread().getId() + " value = " +
        tracker.get() + " test-method = " + testMethod);
    }
}
```

Test class

```java
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import static com.rationaleemotions.github.issue3044.SampleListener.tracker;

@Listeners(SampleListener.class)
public class SampleTestCase {

    @Test(timeOut = 1000L)
    public void a() {
        System.err.println("[a()] Thread id " + Thread.currentThread().getId() + " value = " + tracker.get());
    }

    @Test
    public void b() {
        System.err.println("[b() ]Thread id " + Thread.currentThread().getId() + " value = " + tracker.get());
    }
}
```

suite file

```xml
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="2980_suite" verbose="2" parallel="methods">
    <test name="2980_test" verbose="2" parallel="methods">
        <classes>
            <class name="com.github.issue3044.SampleTestCase"/>
        </classes>
    </test>
</suite>
```

Output

```bash
...
... TestNG 7.9.0 by Cédric Beust (cedric@beust.com)
...

Setting the initial value :6c5c8d77-5b92-4281-b550-3cef65fdd168
Setting the initial value :2f705c3f-4326-44f5-93ba-af58e94afbc0
[beforeInvocation()] Thread id 15 value = 2f705c3f-4326-44f5-93ba-af58e94afbc0 test-method = a
[beforeInvocation()] Thread id 16 value = 6c5c8d77-5b92-4281-b550-3cef65fdd168 test-method = b
[a()] Thread id 15 value = 2f705c3f-4326-44f5-93ba-af58e94afbc0
[b() ]Thread id 16 value = 6c5c8d77-5b92-4281-b550-3cef65fdd168
PASSED: com.rationaleemotions.github.issue3044.SampleTestCase.b
PASSED: com.rationaleemotions.github.issue3044.SampleTestCase.a

===============================================
    2980_test
    Tests run: 2, Failures: 0, Skips: 0
===============================================


===============================================
```

**Comment by asolntsev** [comment]
@krmahadevan Thank you for the quick reply. Will continue in #914 .

P.S. No, `InheritableThreadLocal` doesn't help because the "after" method who needs to check to threadlocals is executed in "main" thread. Thus, it sees only the "parent" thread's ThreadLocal which stays empty (tests add values only to "child" thread's ThreadLocals).

**Comment by asolntsev** [comment]
@krmahadevan Thanks, but it didn't help.
Added methods `beforeInvocation` and `afterInvocation` are still executed in different thread (compared to test).
I committed my changes to https://github.com/asolntsev/testng-threads-sample/

**Comment by krmahadevan** [comment]
@asolntsev - I forgot to call out one important aspect. The `parallel` is set to `methods` in the suite file. So can you please alter your gradle build file and configure TestNG as below and try again? 

```groovy
test {
    useTestNG {
        options ->
            options.parallel = 'methods'
    }
}
```

**Comment by asolntsev** [comment]
@krmahadevan Yes, after adding `parallel = 'methods'` "before" and "after" methods are executed in the same thread with test. 
But
1. What if I don't want to run tests in parallel?
2. What about all these arguments from https://github.com/testng-team/testng/issues/914#issuecomment-1914610207 that "it breaks contract", "its going to be unfair" etc. ?

**Comment by krmahadevan** [comment]
Yes thats the caveat that we have to use parallel as methods to get this to work which is not optimal. 

I believe for the other part i have added my thoughts as a reply to your comment.
