### ISSUE TITLE
Add support of java 21 LTS

### ISSUE THREAD

**Issue by juherr** [testng-team/testng#3055]
and drop support of java 11 LTS.

**Comment by krmahadevan** [comment]
@juherr - What should be the target version for this and does this issue mean that once this is fixed, TestNG will require atleast JDK21 ?

**Comment by juherr** [comment]
TestNG supports the 2 latest LTS then 17 as baseline and 21.

**Comment by krmahadevan** [comment]
@juherr - Sorry. I didn't understand.

Can you please clarify the expectations? 

* The changes for this PR will ensure that TestNG requires which least version of JDK? (Is it JDK17 or JDK21)?
* When do you think we should be making these changes? Should it be part of TestNG 8 series, or can it be part of TestNG 7.x series itself?

It will be useful if you can please elaborate your thoughts around these aspects.

**Comment by juherr** [comment]
The expectation is to use java17 as base.
Java 21 must be supported too.

The ticket could be done in 2 steps:
1. Add java21(in current testng version)
2. Drop java11 (in a new major testng version)

**Comment by krmahadevan** [comment]
Regarding the add `java21` in current TestNG version, can you please add more details regarding this? 

I am not sure if we can use the JDK21 features as is without bumping the required version to JDK21.

**Comment by juherr** [comment]
Add support of Java 21 just means to add it as a target in CI.

**Comment by vlsi** [comment]
https://github.com/testng-team/testng/pull/3067 added CI tests with Java 21 and 22, so this issue can probably be resolved
