### ISSUE TITLE
How to enable generateTestResultAttributes programatically using Java ?

### ISSUE THREAD

**Issue by pothurajtharun** [testng-team/testng#3070]
### TestNG Version
7.9.0

### Expected behavior
Custom attributes should be present in the XML report.

### Actual behavior
Custom attributes are not present in the XML report.

### Is the issue reproducible on runner?

- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
I have a setup that i will build my project as a Jar with dependencies and run the automated test cases with java commands like below. I used OpenJDK 21.

```
java \
-Diterations=$ITERATIONS \
-DconfigFilePath=$env/mac/mac_install.yml \
-DxmlSuiteFile=testng_tiny_install_app.xml \
-Ddataset=$env/mac/web_chrome_$env.properties \
-jar $WORKSPACE/target/kepler-client-test-automation-jar-with-dependencies.jar
``` 
I saw a [comment](https://github.com/testng-team/testng/issues/1673#issuecomment-362893227) there is a way using maven-sure-fire plugin to enable `generateTestResultAttributes`. But is there a way to enable the same programmatically without using maven-sure-fire plugin ?

After executions are completed the `testng-results.xml` file has no attributes.

Runner
```
private static boolean runSuites(
      List<XmlSuite> xmlSuites, Integer iterations, Integer intervalBetweenIterations) {
    log.info("Running Suites has started");
    // Main Runner
    TestNG testRunner;
    boolean hasFailure = false;

    // Start the runner
    testRunner = new TestNG();
    if (SystemUtil.getIsReportPortalEnabled()) {
      testRunner.addListener(new ReportPortalTestNGListener());
    }
    log.debug("Initiating a TestNG Runner");
    updateXmlSuiteIndex(xmlSuites);
    testRunner.setXmlSuites(xmlSuites);
    log.debug("TestNG Runner has started");
    testRunner.run();
    hasFailure |= testRunner.hasFailure();
    log.debug("TestNG Runner has ended");
    return hasFailure;
  }

  private static void updateXmlSuiteIndex(List<XmlSuite> xmlSuites) {
    xmlSuites.forEach(
        xmlSuite -> {
          if (xmlSuite.getChildSuites().isEmpty()) {
            xmlSuite.getParameters().put("index", IndexCounter.increment() + "");
            xmlSuite.setGuiceStage("DEVELOPMENT");
          } else {
            xmlSuite.getChildSuites().forEach(AutomatedTestingRunner::setIndex);
          }
        });
  }
```

Test Method
```
@Test
public void welcomeTesting() {
    if (OsHelper.IOS_PLATFORM
        && WaitHelper.isElementAppearedWithinTimeout(uiController, ftuePage.getAllowButton(), 5L)) {
      waitAssertTap(uiController, ftuePage.getAllowButton());
    }
    assertElementIsVisible(uiController, ftuePage.getWelcomeFtueDescription());
    ITestResult result = Reporter.getCurrentTestResult();
    result.setAttribute("test", "XRY-6");
  }
```

Please help me where exactly i have to set the `generateTestResultAttributes` flag to true, to make the attributes available in testng-results.xml file.

Thanks!

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
Assuming that we have created a jar and test-jar based on the instructions as explained in the [official documentation](https://testng.org/#_running_tests_from_within_a_test_jar) you would basically get this done by using the below command 

```bash
java -jar target/uber-testjar-demo-1.0-SNAPSHOT-test-jar-with-dependencies.jar \
-testjar target/uber-testjar-demo-1.0-SNAPSHOT-tests.jar \
-reporter org.testng.reporters.XMLReporter:generateTestResultAttributes=true
```
