### ISSUE TITLE
Please document project's PGP artifact signing keys

### ISSUE THREAD

**Issue by iay** [testng-team/testng#3084]
### TestNG Version

7.9.0

### Expected behavior

As a developer in a project dependent on TestNG, I should be able to verify the PGP signature on TestNG artifacts downloaded from Maven Central.

### Actual behavior

Recent TestNG artifacts appear to be signed by this PGP key:

```
gpg: Signature made Tue Dec 26 09:36:16 2023 GMT
gpg:                using RSA key 0F13D5631D6AF36D
gpg: Good signature from "Krishnan Mahadevan (krmahadevan-key) <krishnan.mahadevan1978@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: C4F5 4D86 22C9 5CC3 F098  721A 0F13 D563 1D6A F36D
```

This key claims to be associated with a member of the TestNG team, but due diligence in supply chain security requires us to demonstrate this more directly (anyone could create a PGP key _claiming_ to belong to a TestNG team member and upload it to the key servers).

It would really help us out if the list of keys which can sign project artifacts on Maven Central was made available either within the repository itself (commonly as a KEYS file containing ASCII-armoured key exports) or in the documentation (as the same thing, or using full key fingerprints).

**Comment by krmahadevan** [comment]
@iay - Since I dont have a lot of context around what you are asking for, would it be possible for you to please help walk me through on how to get these steps done? The keys that you called out belongs to me and I am part of the TestNG dev team. Please feel free to get as elaborate as you can :) I can use all the help that you can provide

**Comment by iay** [comment]
No problem, I quite understand. The easiest way to do this is to crib the procedure from the Apache folks' [Signing Releases](https://infra.apache.org/release-signing.html) document's section on [The Keys File](https://infra.apache.org/release-signing.html#keys-policy). They describe the sort of thing that usually goes in a KEYS file, including a useful header and how to add your own key to the file including example `gpg` commands.

In your case, you could create a KEYS file with just their suggested header and then add your key like this:

```bash
(gpg --list-sigs krishnan.mahadevan1978@gmail.com && \
 gpg --armor --export krishnan.mahadevan1978@gmail.com) >>KEYS
```

The Apache projects have a convention of storing each project's KEYS file in their download area, but in your case I suggest just committing it to the top level of the repository.
