### ISSUE TITLE
Group execution interrupted by another group

### ISSUE THREAD

**Issue by schroeca** [testng-team/testng#3133]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
All tests in a group shall be executed before another @BeforeGroups is called.

### Actual behavior
Some tests in a group are executed, and the before groups method gets called in the middle of the execution of a different group.

### Is the issue reproducible on runner?

- [ ] Shell
- [x ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
@schroeca Can you please share a sample project that can be used to reproduce the problem?

**Comment by krmahadevan** [comment]
No response from user. Closing this issue.
