### ISSUE TITLE
Class not found org.testng.TestNGAntTask  on updating TestNg to 7.10.0 and above

### ISSUE THREAD

**Issue by AutomationRia** [testng-team/testng#3134]
### TestNG Version
7.10.0 and above

### Expected behavior
The user should be able to execute Test using the TestNGAntTask task

### Actual behavior
Getting error Class not found org.testng.TestNGAntTask

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Below line code throws error now 

` <taskdef name="testng" classname="org.testng.TestNGAntTask" classpathref="classpath">
</taskdef>
`
![image](https://github.com/testng-team/testng/assets/43615975/af09ab4d-2bde-4007-a7a9-401ad5279003)

dependency : 
`<dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.10.0</version>
        </dependency>`
classpath is defined in code and code works fine fine with TestNg version  below 7.10.0

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
This was called out as part of the release notes of TestNG `7.10.0`. Please see https://groups.google.com/g/testng-users/c/6DmFaKUjIxY

The Ant specific changes now reside in a separate repo https://github.com/testng-team/testng-ant

You should be able to build and use it (It's a maven project).

@juherr - Thoughts?

**Comment by juherr** [comment]
@AutomationRia I'm surprised that someone still using ant. 

Could you share with us your specific context?

@krmahadevan Maybe we can plan to make a release of the ant project.

**Comment by krmahadevan** [comment]
@juherr - Release as in regular artifact or as a fat jar for this project?

Also does it need to be deployed in maven central or just publish it to github releases would do?

**Comment by juherr** [comment]
@juherr a regular jar sounds better because it will work with future testng version (except if the cli api change)

**Comment by krmahadevan** [comment]
@AutomationRia - You should be cloning https://github.com/testng-team/testng-ant and then running `./mvn clean package`

**Comment by krmahadevan** [comment]
@AutomationRia - Testng-ant is now released and is available on Maven central https://repo1.maven.org/maven2/org/testng/testng-ant/1.0.0/
