### ISSUE TITLE
Test methods skipped after failed AfterMethod

### ISSUE THREAD

**Issue by TobiasAdler** [testng-team/testng#3139]
In a test class if there is an AfterMethod that fails, all the following test methods are skipped and contain the context from the assertion error of the failed AfterMethod.

### TestNG Version
7.10.2

### Expected behavior
All test methods should pass and only the AfterMethod should fail.

### Actual behavior
The test methods that should be executed after the first one are skipped and contain the error context of the failed AfterMethod.

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```
public class TestClass {
    @BeforeMethod
    public void beforeMethod() {}

    @AfterMethod
    public void afterMethod() {
        Assert.fail("AfterMethod fails");
    }

    @Test
    public void test01() {}

    @Test
    public void test02() {}

    @Test
    public void test03() {}
}
```
I used the Allure report (allure-testng v2.19.0 & gradle allure-report-plugin v2.11.2) to visualize the behavior.
As visible in the screenshot, `test02` and `test03` are skipped after `afterMethod` failed and the methods contain the assertion error "AfterMethod fails".

![allure-report](https://github.com/testng-team/testng/assets/113340362/aa3093e7-5bd2-47f5-bd8a-eb258c383da6)

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
Please set `configfailurepolicy="continue"` in your suite file to ensure that the remaining tests are executed.
