### ISSUE TITLE
NPE when retrieving Retry analyzer if none is defined

### ISSUE THREAD

**Issue by javydreamercsw** [testng-team/testng#3145]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Graciously return either null or a NoOp retry analizer.

### Actual behavior
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "this.m_retryAnalyzerClass" is null

	at org.testng.internal.BaseTestMethod.getRetryAnalyzerConsideringMethodParameters(BaseTestMethod.java:828)

	at org.testng.internal.BaseTestMethod.getRetryAnalyzer(BaseTestMethod.java:693)
As you can see in the code below if m_retryAnalyzerClass is null a NPE will be thrown in line 828.

![Screenshot 2024-06-27 at 3 50 24 PM](https://github.com/testng-team/testng/assets/2817343/28fe07d4-5c72-494d-a4e6-a8efb797194c)

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by javydreamercsw** [comment]
- TestNG 7.10.2
- JDK 17
- Maven/IntelliJ
- Can't share due to proprietary things in it.
Sadly I was unable to reproduce outside of our proprietary code how that variable ends up being null but it started happening when moving from 7.10.0

**Comment by krmahadevan** [comment]
@javydreamercsw without a sample not sure what can be done. 

Please feel free to add a comment once you have a sample that can be used to reproduce the problem. Until then most likely we will close this issue.
