### ISSUE TITLE
Error while downloading DTD.

### ISSUE THREAD

**Issue by saurabh-Dmart** [testng-team/testng#3146]
TestNG Version
> 7.10.2

## Getting DTD error on testng.xml

Error while downloading 'https://testng.org/testng-1.0.dtd' to 'C:  \Users\saurabh.sonawane\.lemminx\cache\https\testng.org\testng-1.0.dtd' : '[java.net.ConnectException] Connection timed   out: connect'.

I think this is because my organization blocks the test-ng website for access so how can i manually do it ?

- Using Eclipse IDE.

**Comment by krmahadevan** [comment]
@saurabh-Dmart - Please submit TestNG eclipse plugin related issues to https://github.com/testng-team/testng-eclipse

When you file the issue, please also include details of versions for

* eclipse
* eclipse testng plugin
* TestNG version that you are using
