### ISSUE TITLE
onStart (ITestListener) is executed one time before the first class in package

### ISSUE THREAD

**Issue by maksim-kanin** [testng-team/testng#3147]
### TestNG Version

7.10.0

### Expected behavior

onStart is executed before all tests for each class in test run

### Actual behavior

onStart is executed one time before the first class in test run

### Is the issue reproducible on runner?
- [ ] Gradle 8.0

### Test case sample
Assuming we have 2 classes in one package with tests Test1 and Test2. I've implemented ITestListeners and willing to use onStart, onTestStart methods from there:
```kotlin
class Listener : ITestListener {
    override fun onTestStart(result: ITestResult?) {
        println("onTestStart: ${result?.name}")
    }

    override fun onStart(context: ITestContext?) {
        println("onStart: ${context?.allTestMethods?.first()?.instance?.javaClass?.name}")
    }
}
```

```kotlin
@Listeners(Listener::class)
class TestClass1 {
    @Test
    fun test1() {

    }

    @Test
    fun test2() {

    }
}
```

```kotlin
@Listeners(Listener::class)
class TestClass2 {

    @Test
    fun test1() {

    }

    @Test
    fun test2() {

    }
}
```
Expected output:
onStart: TestClass1
onTestStart: test1
onTestStart: test2
onStart: TestClass2
onTestStart: test1
onTestStart: test2
 
Actual output:
onStart: TestClass1
onTestStart: test1
onTestStart: test2
onTestStart: test1
onTestStart: test2

- Kotlin 1.9.22 (Java 17)
- TestNG version 7.10.0 (7.9.0)

Thank you in advance for an answer, i do believe i interprete documentation right... If not, could you, please, suggest how to achieve an expected behavior with listeners

**Comment by krmahadevan** [comment]
@maksim-kanin - The `onStart(ITestContext)` is supposed to be executed ONLY once per `<test>` tag. Since you have included the same listener class on each of the 2 test classes, TestNG evaluates this to only 1 listener and executes its `onStart(ITestContext)` once. 

If you are looking at doing something before a class, you could perhaps try implementing `IClassListener`. For more details please check https://testng.org/#_listening_to_class_level_invocations

**Comment by krmahadevan** [comment]
Does that satisfy your ask ? Please let us know

**Comment by maksim-kanin** [comment]
Hi, @krmahadevan Thank you for your help, IClassListener was exactly what i've been looking for!
