### ISSUE TITLE
ITestContext Does Not Work in BeforeSuite Anymore

### ISSUE THREAD

**Issue by ryramos** [testng-team/testng#3183]
### TestNG Version
7.10.2

### Expected behavior
ITestContext cannot be passed as a parameter anymore in BeforeSuite method

### Actual behavior
This used to work and allow us to get and print information about how the test execution will behave 

### Is the issue reproducible on runner?
- [ ] Gradle
- [ ] IntelliJ

### Description
We want to print some information before the start of the test suite like the parallel mode and thread-count. See our implementation below which used to work until recently. I suspect that the issue started with #2933. The workaround is to put ITestContext in some other @Before method. However, this has the tendency to get executed multiple times (let's say in @BeforeGroup method and there happens to be multiple groups in the test suite). 
```
@BeforeTest(alwaysRun = true)
public static void getSuiteContext(ITestContext context) {
     System.out.println("Suite Parallel mode: " + context.getSuite().getXmlSuite().getParallel().toString()); 
     System.out.println("Suite Thread count: " + context.getSuite().getXmlSuite().getThreadCount());
}
```

**Comment by krmahadevan** [comment]
Someone very recently asked a similar question. 

Please refer to this thread for a working sample https://groups.google.com/g/testng-users/c/wIen9Z85_YI/m/lDeisTpOCAAJ

**Comment by juherr** [comment]
Thanks for the report. 

ITestContext is no more supposed to be injectable everywhere.

But we can think about making XmlSuite or ISuite injectable.

Will it be a working workaround for you?

**Comment by ryramos** [comment]
> Thanks for the report.
> 
> ITestContext is no more supposed to be injectable everywhere.
> 
> But we can think about making XmlSuite or ISuite injectable.
> 
> Will it be a working workaround for you?

I think allowing XmlSuite or ISuite to be injectable can work for my use case :). Thanks for suggesting this. Do we need to reopen this issue then?

**Comment by juherr** [comment]
@krmahadevan There is an issue in the documentation https://testng.org/#_native_dependency_injection

> Any @Before method or @Test method can declare a parameter of type ITestContext

As `XmlTest` is already injectable, what do you think to make it available for `XmlSuite` and/or `ISuite` everywhere too?

**Comment by krmahadevan** [comment]
@ryramos 

> But I'm not sure if the above is more of a workaround, and if the proper resolution is to still eventually allow XmlSuite or ISuite to be injectable in BeforeSuite.

It's not a workaround. We are using only documented apis to retrieve the `<suite>` object representation.

**Comment by ryramos** [comment]
Ok, I'm just glad I have a working code now. Although I'm a little concerned as it seems not a few people has been injecting ITestContext in BeforeSuite for years and they will find their code suddenly not working when they update their TestNG.

Anyway, thanks to you both :)
