### ISSUE TITLE
AfterClass method isn't fired when an IMethodInterceptor removes test methods

### ISSUE THREAD

**Issue by jpgreenfield** [testng-team/testng#392]
This issue was fixed in https://github.com/cbeust/testng/issues/90, but not completely, hence my filing of this bug report. I also noticed that ticket https://github.com/cbeust/testng/issues/274 seems to be the issue I'm filing here, but since it contains almost no details, it's hard to say for sure.

This issue is that when methods are removed in an IMethodInterceptor listener class, then AfterClass methods will not be fired for the test class the methods were removed from. I took a brief look at the TestNG source, and this seems to occur because the mapping of test classes to methods is set early (i.e. the m_classMethodMap) in the initialization of TestNG and seemingly never updated/synced to possible changes made by the listener. So, later when the IMethodInterceptor removes a few methods from the run for a particular test class, TestNG doesn't know about it. TestNG will not fire the AfterClass method because it is still expecting additional methods to be run before it will fire the AfterClass method. But, since those other methods will never be run, the AfterClass method can never be run.

I'll attach a self-contained package (with usage README) showing the issue on the Dev mailing list right after I submit this ticket.

I'd appreciate any help you can provide on a fix for this. Thanks!

**Comment by juherr** [comment]
Seems fixed by #525
