### ISSUE TITLE
If test methods are filtered using IMethodInterceptor, beforeclass method is not executed

### ISSUE THREAD

**Issue by sendami-tech** [testng-team/testng#521]
I have been investigating when this bug is happening, and it's when for inside a test class the IMethodInterceptor selects not all the test methods, so when this is happening not all the test methods from the test class are going to be executed. 

The problem is when the method "protected void invokeAfterClassMethods(ITestClass testClass, IMethodInstance mi)" is called. Here, to indicate the we are in the last method is checking against all the methods of the test class instead of the set of test methods that IMethodInterceptor has selected. This is done when the method m_classMethodMap.removeAndCheckIfLast(tm, mi.getInstance()) is called, so mi.getInstance() returns all the test methods from the test class. 

I hope you understand what is happening. Let me know please if you need any more clarification. 

Cheers

**Comment by juherr** [comment]
I don't reproduce the problem. As #392 I suppose it was fixed by #525
