### ISSUE TITLE
ability to xinclude in testng files

### ISSUE THREAD

**Issue by tinnyatpardot** [testng-team/testng#542]
Hi Guys,

This is related to defect  95 with this description:

Add ability to include XML files (XInclude)

I know this defect was closed because of the ability to use suite-files but that is only allowed at the suite level.  It doesn't allow for lots of flexibility say having the ability to split out a ton of common parameters and classes used across several <test> cases into another xml file.  Can the solution proposed in that defect (which makes the xml parser xinclude aware) be used?  Thanks a bunch!

**Comment by krmahadevan** [comment]
Almost all of the capabilities with respect to altering suite can be achieved via the TestNG listener `org.testng.IAlterSuiteListener`
