### ISSUE TITLE
Parameters of nested test suites are overriden

### ISSUE THREAD

**Issue by chillinPanda** [testng-team/testng#581]
# Github Demo Project with bug

I wrote a little demo project to show you this problem and that you can play and interact with it. There are also more information on the readme.md.
Check out https://github.com/chillinPanda/testng-parameter-error
# Problem

If I nest two test suites into one and use parameter in the nested suite-file definition, those are overriden by following same-name-parameters. In the following example "www.wikipedia.org" will be overriden to "www.google.com" and then the tests at src/test/testng_xmls/testng_wiki.xml get a wrong parameter (the one from below)

``` xml
<suite name="Demo" parallel="tests">
  <suite-files>

    <suite-file path="src/test/testng_xmls/testng_wiki.xml">
      <parameter name="url" value="www.wikipedia.org" />
    </suite-file>

    <suite-file path="src/test/testng_xmls/testng_google.xml">
      <parameter name="url" value="www.google.com" />
    </suite-file>

  </suite-files>
</suite>
```

**Comment by krmahadevan** [comment]
`<parameter>` is not supposed to be passed from within the `<suite-file>`. But there's a parsing bug in TestNG owing to which TestNG ends up reading the parameter (which it should never have).

That has been fixed as part of this PR https://github.com/testng-team/testng/pull/2923

**Comment by krmahadevan** [comment]
Also we have tightened the dtd file via https://github.com/testng-team/testng-team.github.io/pull/46 and released a new version of it at http://testng.org/testng-1.1.dtd

We have also enriched the codebase to now refer to the tighthened DTD `testng-1.1.dtd` as an embedded DTD within the TestNG codebase as part of the PR https://github.com/testng-team/testng/pull/2923
