### ISSUE TITLE
Allow multiple IMethodInterceptors

### ISSUE THREAD

**Issue by jharting** [testng-team/testng#601]
There seems to be a limitation that only the last IMethodInterceptor listed in the xml file will be used. It would be more useful if several independent interceptors could be registered, cooperating via a shared context if needed.

**Comment by juherr** [comment]
#625 seems to fix what you ask

**Comment by jharting** [comment]
Yes exactly. Hopefully it gets merged soon!

**Comment by juherr** [comment]
Duplicate of #625
