### ISSUE TITLE
[selenium:testng] Total tests run: 0, Failures: 0, Skips: 0 on suite timeout with hardAssert?

### ISSUE THREAD

**Issue by cktech1me** [testng-team/testng#669]
I'm seeing the following behavior:

```
TestName
[selenium:testng] Total tests run: 0, Failures: 0, Skips: 0
```

My `testng.xml` file points to a bunch of suite files using  suite-files / suite-file path = test1, test 2 etc.

Each of those files is a FireFox <test></test>

```
    test name="Firefox-WINDOWS-7"
        classes
            class name="UIAutomationTest"
        classes
    test
```

UIAutomationTest has a `@BeforeMethod` Setup, `@Test` and `@AfterMethod` tearDown where I call `driver.quit();`

In the test I have something like:

``` java
    // wait till UI resets and next test starts
            try {
                Thread.sleep(5000);
            } catch (InterruptedException e) {
                hardAssert.fail("Sleep Interrupt: We most likely hit the testng timeout set by suite.windows.timeout in build.properties", e.getCause());
            }
```

hardAssert is defined as: Assertion hardAssert = new Assertion();

hardAssert 
I see in logs that test X has 'failed' and onTestFailed was called...

On the report and console I see the above 
0, 0, 0 - pass, fail, skip result

The test clearly failed because I'm capturing some logs and get:

```
STARTED - testSuite - Test1 @ 09:20:13:850
@TEST - Test1 - Firefox-WINDOWS-7 - 3a376c0b-4bf1-4842-a09a-161b0d2dfdf2
FAILED - testSuite - Test1 @ 09:21:10:918
java.lang.AssertionError: Sleep Interrupt: We most likely hit the testng timeout set by suite.windows.timeout in build.properties
org.testng.Assert.fail(Assert.java:83) (with others of org.testng.* omitted)
UIAutomationTest.testSuite(Unknown Source)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (with others of java.lang.reflect.* or sun.reflect.* omitted)
java.util.concurrent.FutureTask.run(FutureTask.java:262)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:745)
TEARDOWN -Test1- Firefox-WINDOWS-7 - 3a376c0b-4bf1-4842-a09a-161b0d2dfdf2
```

Other tests, same Failure case, show up as a RED failure on the report

```
Firefox-WINDOWS-7   71.828s 0   0   1   0%
Failed Tests
UIAutomationTest
testSuite   62.252s Method arguments: org.testng.TestRunner@2076b1a9
@TEST - Test2- Firefox-WINDOWS-7 - 9ced1e4a-9c5f-45be-b90c-6b4ff47fc43a
FAILED - testSuite - Test2 @ 09:20:14:095
java.lang.AssertionError: Sleep Interrupt: We most likely hit the testng timeout set by suite.windows.timeout in build.properties
org.testng.Assert.fail(Assert.java:83) (with others of org.testng.* omitted)
UIAutomationTest.testSuite(Unknown Source)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) (with others of java.lang.reflect.* or sun.reflect.* omitted)
java.util.concurrent.FutureTask.run(FutureTask.java:262)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:745)
```

Yet at the console they still show:

```
[selenium:testng] ===============================================
[selenium:testng] 
Test2
[selenium:testng] Total tests run: 0, Failures: 0, Skips: 0
[selenium:testng] ===============================================
```

The REPORT (ReportNG for example) 

Always shows

```
[selenium:testng] ===============================================
[selenium:testng] 
Default Suite
[selenium:testng] Total tests run: 0, Failures: 0, Skips: 0
[selenium:testng] ===============================================
```

The Console shows the total counts:

```
[selenium:testng]
[selenium:testng] ===============================================
[selenium:testng] Default Suite
[selenium:testng] Total tests run: 15, Failures: 12, Skips: 0
[selenium:testng] ===============================================
```

I just tested against the latest snapshot, no luck.

**Comment by juherr** [comment]
Could you give us a little similar project we are able to run and which reproduces the issue?

Or try the user mailing list.

**Comment by cktech529** [comment]
Sure, let me pull something together. Thanks!

**Comment by cktech529** [comment]
Where would I upload say a zip containing a project with the issue?

**Comment by juherr** [comment]
Just create a repository on your github space ;)

**Comment by cktech529** [comment]
Here's the example (with example testng.xml, report output and java code) 

https://github.com/cktech529/timeoutissue

The suite level timeout is 30 seconds
The Thead.sleep time is 250 seconds, so testng times out as it should with 

hardAssert.fail("Sleep Interrupt: We most likely hit the testng timeout set by suite.windows.timeout in build.properties", e.getCause());

Yet the test on a few occasions doesn't FAIL and thus isn't reported as a failure...

When called via ANT I used:
  useDefaultListeners="false"
  failureProperty="tests.failed"
  skippedProperty="tests.skipped"
  haltonfailure="false"
  suiteThreadPoolSize="5"

**Comment by cktech529** [comment]
I've also noticed when I target the latest testng using ant I see:

[selenium:testng] ... TestNG 6.8.2beta_20130330_0839 by CΘdric Beust (cedric@beust.com)

I'm using:

    <taskdef name="testng"
             classname="org.testng.TestNGAntTask"
             uri="antlib:com.emc.dependencies.ant.selenium"
             description="Config for automation testng tests" >
        <classpath>
            <pathelement location="${selenium.dir}/libs/testng-6.8.22-SNAPSHOT.jar"/>
        </classpath>
    </taskdef>

**Comment by cktech529** [comment]
I tried something different, more strange results

https://github.com/cktech529/timeoutissue (the singleSuite folder.)

**Comment by cktech529** [comment]
The same above test running with parallel and thread-count turned off (reports back as expected.)

Default Suite
 	Duration	Passed	Skipped	Failed	Pass Rate
Firefox-WINDOWS-1	39.546s	0	0	1	0%
Firefox-WINDOWS-2	39.307s	0	0	1	0%
Firefox-WINDOWS-3	38.931s	0	0	1	0%
Firefox-WINDOWS-4	38.965s	0	0	1	0%
Firefox-WINDOWS-5	38.785s	0	0	1	0%
Firefox-WINDOWS-6	38.643s	0	0	1	0%
Firefox-WINDOWS-7	38.823s	0	0	1	0%
Total	0	0	7	0%

**Comment by ailyenko** [comment]
Any updates on this issue?

**Comment by juherr** [comment]
Nope, sorry.

**Comment by nitishsajnani** [comment]
Check your test annotation it always should be "@Test"

**Comment by krmahadevan** [comment]
Tried to reproduce this issue using TestNG `7.8.0` (with the below project) and can't recreate the issue. If the issue persists using `7.8.0` please comment and share a sample reproducible to recreate issue.
[timeoutissue.zip](https://github.com/testng-team/testng/files/11664888/timeoutissue.zip)
