### ISSUE TITLE
Create an AppVeyor account

### ISSUE THREAD

**Issue by juherr** [testng-team/testng#713]
To activate AppVeyor CI, the project must be connected to an AppVeyor account.
I can use mine but I think it will be better if you have your own one.

**Comment by cbeust** [comment]
Yes, I'll take care of it. Thanks, @juherr !

**Comment by krmahadevan** [comment]
ping @cbeust - Can you please help take care of this, so that we can have this closed? I guess @juherr has already added an https://github.com/cbeust/testng/blob/master/appveyor.yml

Trying to close off all issues and clean-up our issue list

**Comment by krmahadevan** [comment]
Closing this ticket since we are now using Github actions for our CI needs and it is sufficient for our user case.
