### ISSUE TITLE
Dataprovider TestNG Reporting Issue

### ISSUE THREAD

**Issue by Jayaram1988** [testng-team/testng#730]
Consider a selenium Java script that is run parallel  using data provide for n iterations and some of them has failed. TestNG report does show all n iterations in both passed and failed section.

**Comment by juherr** [comment]
Which kind of reporter? Eclipse, xml,...?

**Comment by Jayaram1988** [comment]
we have run the scripts from Eclipse, the report I am referring is the TestNG default report

**Comment by krmahadevan** [comment]
If this is still a problem please file issue at https://github.com/testng-team/testng-eclipse/issues
