### ISSUE TITLE
DataProvider Running Parallel Tests Sometimes Runs Tests Marked As Skipped

### ISSUE THREAD

**Issue by jbragiel** [testng-team/testng#731]
We are seeing intermittent failures during some of our test runs.  The failures are caused by tests that should be skipped, but are shown by TestNG as failed.  When a skipped test fails, it is because the test method is getting run by TestNG and failing instead of being skipped.

We originally saw this issue in 6.8.8, but it does still exist in 6.9.4.  It looks like the use of a DataProvider and parallel execution triggers the behavior.  Here's a simple sample test class that exhibits the behavior:

```
package mysample;

import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.SkipException;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import org.testng.internal.Utils;

import java.lang.reflect.Method;
import java.util.Random;

public class SkipExample {
    private int count = 0;

@BeforeMethod(alwaysRun = true)
public void beforeMethod(ITestContext context, ITestResult result, Method method, Object[] arguments) {
    int instanceNum = count++;
    Random rand = new Random();

    log(2, "beforeMethod - Running beforeMethod(" + instanceNum + ")");
    log(2, "beforeMethod - beforeMethod(" + instanceNum + ") is throwing a SkipException.");
    throw new SkipException("My test(" + instanceNum + ") should be skipped.");
}

private void log(int level, String s) {
    Utils.log("SkipExample " + Thread.currentThread().hashCode(), level, s);
}

@Test(dataProvider = "test1")
public void testMethod(String str, Integer num) {
    String bad = null;
    bad.equals("broken");
}

@DataProvider(name = "test1", parallel = true)
public Object[][] createData1() {
    return new Object[][] {
            { "Cedric", 36 },
            { "Anne", 37},
            { "John", 38},
            { "Eric", 39}
    };
}
```

}

The class is run with command line parameters:
`-configfailurepolicy continue -testclass mysample.SkipExample -log 3`

Analysis of the code in org/testng/internal/Invoker.java points to the use of getMethodInvocationToken(ITestNGMethod method, Object instance) as the possible problem.  The token returned is created by creating a string made up of the TestInstance.toString() combined with the number of times the test method *\* has completed**.

In one failed scenario, all four of the parallel running tests throw their SkipExceptions before any of the four tests complete.  So, all four skips are registered with m_methodInvocationResults as the token "mysample.SkipExample@5a3f4547+0" in the method setMethodInvocationFailure().  Using the same token 4 times could be incorrect but isn't necessarily causing the issue with running tests that should be skipped.

Continuing on with the scenario, after the configuration is complete, in invokeMethod(), the results of the configuration step are used to determine whether the test should be run.  The method that determines configuration success is confInvocationPassed().  It determines configuration success by retrieving the token again with getMethodInvocationToken and seeing if that token is in the failed list.  This logic assumes the the same token used during the configuration phase will be used to check configuration results.  But if any of the parallel running four tests complete, the token will not be the same.  It will be something like "mysample.SkipExample@5a3f4547+1" instead.  Each time a test completes, the number after the + in the token will be incremented.  If the token mismatch happens, the test will be run when it should be skipped.

**Comment by krmahadevan** [comment]
Attempted at reproducing this issue using TestNG `7.8.0` and I am not able to. Please comment if this is still a problem.
