### ISSUE TITLE
context.getFailedTests().getAllResults() call in overridden ITestListener.onFinish() does not return correct number of failed tests

### ISSUE THREAD

**Issue by johnmak-veeva** [testng-team/testng#786]
I'm using a RetryListener for retry on failed tests with a TestListener which removes any duplicate results for retries.  However I see an issue when I have a test that failed a total of 3 times (retrying twice), the context.getFailedTests().getAllResults() call in my overridden ITestListener.onFinish() does not return correct number of failed tests.  It only returns 2 failed tests instead of 3.  But in the output console TestNG does show 3 failed tests.

**Comment by rschmitt** [comment]
Which version?

**Comment by johnmak-veeva** [comment]
@rschmitt Using the latest version 6.9.4

**Comment by rschmitt** [comment]
Your TestListener should be unnecessary, since the latest TestNG reports retryable failures as SKIPPED rather than FAILED. (You may need to use 6.9.6-SNAPSHOT to have this fully work, but 6.9.4 at least tries to do it IIRC.)

**Comment by johnmak-veeva** [comment]
Thanks for the help but I figured out the issue. So the TestNG report is displaying the correct adjusted test results but on the console output the re-runs are included in the results.  There seem to be two different results calculation mechanisms here.

**Comment by krmahadevan** [comment]
Closing this issue because there's no sample. If this is still a problem in `7.8.0` (latest released version as of today) please comment with a sample.
