### ISSUE TITLE
Testng Listener invoked more then once

### ISSUE THREAD

**Issue by shroffsagar** [testng-team/testng#910]
Discovered this issue when i had mistakenly configured my listener in testng xml and also via @Listeners.

This is unexpected behaviour as listener logic is invoked twice in entire lifecycle.

Example :
1) Configure ReporterHtmlService (my custom HTMLReporter) in testng.xml
2) Configure ReporterHtmlService in @Listeners(ReporterHtmlService.class)

On executing the tests it invokes ReporterHtmlService twice.

A solution would be to store all TestNG Listeners in a Set<ITestNGListener>. This will make sure that only distinct Listeners are stored.

**Comment by juherr** [comment]
IReporters are already in a set. Did you use testng 6.9.9?

**Comment by juherr** [comment]
Could you pull-request a new test case which shows the issue?
You can add a new test class or update/use an existing one from https://github.com/cbeust/testng/tree/master/src/test/java/test/listeners

**Comment by krmahadevan** [comment]
This should no longer be a problem in TestNG `7.8.0`. Please share a sample reproducible test if this is still a problem.
