### ISSUE TITLE
@BeforeTest method in a super class will be called multiple time when alwayRun = true

### ISSUE THREAD

**Issue by mean-ui-thread** [testng-team/testng#92]
If you have a base test class that contains a method with the annotation @BeforeTest (alwaysRun = true), it will be called by the amount of sub classes added to the testng.xml

I have a little code snippet to help you guys reproduce this issue, but I can't figure out how to attach it to this message...

**Comment by krmahadevan** [comment]
@juherr - I think we can go ahead and close this issue. I tried using the same example that was shared by @mchiasson and I **CANNOT recreate the problem in TestNG 6.10**

Here's my output:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
[XmlSuite] [WARN] 'parallel' value 'false' is deprecated, default value will be used instead: 'none'.
...
... TestNG 6.10 by Cédric Beust (cedric@beust.com)
...

baseTestBeforeTest called
baseTestBeforeTestAlways called
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.314 sec - in TestSuite

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.588 s
[INFO] Finished at: 2016-12-09T23:05:04+05:30
[INFO] Final Memory: 22M/248M
[INFO] ------------------------------------------------------------------------
```

**Comment by juherr** [comment]
@krmahadevan Could you check if a test is covering the use case and propose a new one if not?

**Comment by krmahadevan** [comment]
@juherr - The test `test.bug92.Bug92Test` is covering this.

**Comment by mpvkrishnadhar** [comment]
`public class BaseTest {
	
	@BeforeTest(alwaysRun=true)
	public void BaseTestBeforeTest()
	{
		System.out.println("baseTestBeforeTest called");
	}
	
	@BeforeTest(alwaysRun=true)
	public void BaseTestBeforeTest1()
	{
		System.out.println("baseTestBeforeTestAlways called");
	}


}`
`public class Test_1 extends BaseTest {
	
	@Test
	public void m1()
	{
		//System.out.println("Test1");
		
	}
	
	@Test
	public void m2()
	{
		//System.out.println("Test1");
		
	}

}`
`public class Test_2 extends BaseTest{
	
	@Test
	public void m1()
	{
		//System.out.println("Test2");
		
	}
	
	@Test
	public void m2()
	{
		//System.out.println("Test2");
		
	}

}`
`public class Test_3 extends BaseTest {
	
	@Test
	public void m1()
	{
		//System.out.println("Test2");
		
	}
	
	@Test
	public void m2()
	{
		//System.out.println("Test2");
		
	}

}`
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="1" verbose="1" name="temp Suite" annotations="JDK" parallel="tests">
<test name="Test_1">
	 <classes>
	   <class name="testNGUseCases.Test_1"/>
	 </classes>
   </test>
   
   <test name="Test_2">
	 <classes>
	   <class name="testNGUseCases.Test_2"/>
	 </classes>
   </test>
   
    <test name="Test_3">
	 <classes>
	   <class name="testNGUseCases.Test_3"/>
	 </classes>
   </test>
          
  </suite>`

**output**
baseTestBeforeTest called
baseTestBeforeTestAlways called
baseTestBeforeTest called
baseTestBeforeTestAlways called
baseTestBeforeTest called
baseTestBeforeTestAlways called

===============================================
temp Suite
Total tests run: 6, Failures: 0, Skips: 0
===============================================
is this the correct output?
