### ISSUE TITLE
Impossible to include a suite more than once (regression issue #829)

### ISSUE THREAD

**Issue by harmin-parra** [testng-team/testng#951]
Tested with version 6.9.10

my testng.xml file :

```xml
< suite name="All suites" >
    < suite-files >
        < suite-file path="suite-1.xml"/ >
        < suite-file path="suite-1.xml"/ >
        < /suite-files >
< /suite>
```

The execution output :

```
[testng] [TestNG] [ERROR] 
[testng] Two suites cannot have the same name: My first suite
[testng] The tests failed.
```

https://groups.google.com/forum/#!topic/testng-users/teJVISuBnW8

**Comment by juherr** [comment]
Could you add the test case into https://github.com/cbeust/testng/blob/master/src/test/java/test/sanitycheck/CheckSuiteNamesTest.java and propose it?

**Comment by juherr** [comment]
Similar issue on SO: http://stackoverflow.com/q/43656017/4234729

**Comment by krmahadevan** [comment]
Looks like we are already able to add duplicate suites to a suite file.

The bug https://github.com/cbeust/testng/issues/1850 attempts at doing it and doesn't trigger the edit check.

**Comment by Ericsson-JCAT** [comment]
I don't have the same issue with version 6.9.10 when adding duplicate suites into one parent file.
I think the method "checkSuiteNamesInternal" has already avoided duplicate suite names.

**Comment by krmahadevan** [comment]
Closing this issue. This issue may already have been fixed as a side effect of some other changes.
